# **Major Project**

**INSTALLING CONDA**

In [ ]:
import numpy as np

In [ ]:
! wget  https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
! chmod +x Miniconda3-py39_4.9.2-Linux-x86_64.sh
! bash ./Miniconda3-py39_4.9.2-Linux-x86_64.sh -b -f -p /usr/local
import sys
sys.path.append('/usr/local/lib/python3.9/site-packages/')

--2022-07-15 06:02:49--  https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61451533 (59M) [application/x-sh]
Saving to: ‘Miniconda3-py39_4.9.2-Linux-x86_64.sh’

Miniconda3-py39_4.9 100%[===================>]  58.60M   195MB/s    in 0.3s

2022-07-15 06:02:49 (195 MB/s) - ‘Miniconda3-py39_4.9.2-Linux-x86_64.sh’ saved [61451533/61451533]

PREFIX=/usr/local
Unpacking payload ...
Collecting package metadata (current_repodata.json): - \ | done
Solving environment: - \ | done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - _libgcc_mutex==0.1=main
    - brotlipy==0.7.0=py39h27cfd23_1003
    - ca-certificates==2020.12.8=h06a4308_0
    - certifi==2020.12.5=py39h06a4308_0
    - cffi==1.14.4=py39h261ae71_0
    - chardet==3.0.4=py39h06a4308_1003
    - conda-package-handling==1.7.2=py39h27cfd23_1
    - conda==4.9.2=py39h06a4308_0
    - cryptography==3.3.1=py39h3c74f83_0
    - idna==2.10=py_0
    - ld_impl_linux-64==2.33.1=h53a641e_7
    - libedit==3.1.20191231=h14c3975_1
    - libffi==3.3=he6710b0_2
    - libgcc-ng==9.1.0=hdf63c60_0
    - libstdcxx-ng==9.1.0=hdf63c60_0
    - ncurses==6.2=he6710b0_1
    - openssl==1.1.1i=h27cfd23_0
    - pip==20.3.1=py39h06a4308_0
    - pycosat==0.6.3=py39h27cfd23_0
    - pycparser==2.20=py_2
    - pyopenssl==20.0.0=pyhd3eb1b0_1
    - pysocks==1.7.1=py39h06a4308_0
    - python==3.9.1=hdb3f193_2
    - readline==8.0=h7b6447c_0
    - requests==2.25.0=pyhd3eb1b0_0
    - ruamel_yaml==0.15.80=py39h27cfd23_0
    - setuptools==51.0.0=py39h06a4308_2
    - six==1.15.0=py39h06a4308_0
    - sqlite==3.33.0=h62c20be_0
    - tk==8.6.10=hbc83047_0
    - tqdm==4.54.1=pyhd3eb1b0_0
    - tzdata==2020d=h14c3975_0
    - urllib3==1.25.11=py_0
    - wheel==0.36.1=pyhd3eb1b0_0
    - xz==5.2.5=h7b6447c_0
    - yaml==0.2.5=h7b6447c_0
    - zlib==1.2.11=h7b6447c_3


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  brotlipy           pkgs/main/linux-64::brotlipy-0.7.0-py39h27cfd23_1003
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.12.8-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2020.12.5-py39h06a4308_0
  cffi               pkgs/main/linux-64::cffi-1.14.4-py39h261ae71_0
  chardet            pkgs/main/linux-64::chardet-3.0.4-py39h06a4308_1003
  conda              pkgs/main/linux-64::conda-4.9.2-py39h06a4308_0
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.7.2-py39h27cfd23_1
  cryptography       pkgs/main/linux-64::cryptography-3.3.1-py39h3c74f83_0
  idna               pkgs/main/noarch::idna-2.10-py_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20191231-h14c3975_1
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1i-h27cfd23_0
  pip                pkgs/main/linux-64::pip-20.3.1-py39h06a4308_0
  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py39h27cfd23_0
  pycparser          pkgs/main/noarch::pycparser-2.20-py_2
  pyopenssl          pkgs/main/noarch::pyopenssl-20.0.0-pyhd3eb1b0_1
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.1-hdb3f193_2
  readline           pkgs/main/linux-64::readline-8.0-h7b6447c_0
  requests           pkgs/main/noarch::requests-2.25.0-pyhd3eb1b0_0
  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.80-py39h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-51.0.0-py39h06a4308_2
  six                pkgs/main/linux-64::six-1.15.0-py39h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.33.0-h62c20be_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  tqdm               pkgs/main/noarch::tqdm-4.54.1-pyhd3eb1b0_0
  tzdata             pkgs/main/noarch::tzdata-2020d-h14c3975_0
  urllib3            pkgs/main/noarch::urllib3-1.25.11-py_0
  wheel              pkgs/main/noarch::wheel-0.36.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  yaml               pkgs/main/linux-64::yaml-0.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Preparing transaction: - \ | / done
Executing transaction: \ | / - \ | / - \ | / - \ | / - \ | done
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /usr/local

**Load and Installing Pfeature Library**

In [ ]:
! wget https://github.com/raghavagps/Pfeature/raw/master/PyLib/Pfeature.zip

--2022-07-15 06:03:10--  https://github.com/raghavagps/Pfeature/raw/master/PyLib/Pfeature.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/raghavagps/Pfeature/master/PyLib/Pfeature.zip [following]
--2022-07-15 06:03:10--  https://raw.githubusercontent.com/raghavagps/Pfeature/master/PyLib/Pfeature.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 511222 (499K) [application/zip]
Saving to: ‘Pfeature.zip’

Pfeature.zip        100%[===================>] 499.24K  --.-KB/s    in 0.04s

2022-07-15 06:03:10 (13.3 MB/s) - ‘Pfeature.zip’ saved [511222/511222]

In [ ]:
! unzip Pfeature.zip

Archive:  Pfeature.zip
  inflating: __MACOSX/._Pfeature
  inflating: Pfeature/PKG-INFO
  inflating: __MACOSX/Pfeature/._PKG-INFO
  inflating: Pfeature/.DS_Store
  inflating: __MACOSX/Pfeature/._.DS_Store
  inflating: Pfeature/README
  inflating: __MACOSX/Pfeature/._README
  inflating: Pfeature/setup.py
  inflating: __MACOSX/Pfeature/._setup.py
  inflating: Pfeature/Functions_Tables.pdf
  inflating: __MACOSX/Pfeature/._Functions_Tables.pdf
   creating: Pfeature/build/
  inflating: __MACOSX/Pfeature/._build
  inflating: Pfeature/Pfeature_Descriptors.pdf
  inflating: __MACOSX/Pfeature/._Pfeature_Descriptors.pdf
   creating: Pfeature/Pfeature/
  inflating: __MACOSX/Pfeature/._Pfeature
   creating: Pfeature/build/lib/
  inflating: __MACOSX/Pfeature/build/._lib
  inflating: Pfeature/Pfeature/bonds.csv
  inflating: Pfeature/Pfeature/pfeature.py
  inflating: Pfeature/Pfeature/AAIndexNames.csv
  inflating: Pfeature/Pfeature/aaindices.csv
  inflating: Pfeature/Pfeature/atom.csv
  inflating: Pfeature/Pfeature/PhysicoChemical.csv
  inflating: Pfeature/Pfeature/__init__.py
  inflating: __MACOSX/Pfeature/Pfeature/.___init__.py
  inflating: Pfeature/Pfeature/z_aaindex.csv
  inflating: Pfeature/Pfeature/aaindex.csv
  inflating: Pfeature/Pfeature/bin_di.csv
  inflating: Pfeature/Pfeature/Grantham.csv
  inflating: Pfeature/Pfeature/can_pat.csv
  inflating: Pfeature/Pfeature/aa_attr_group.csv
  inflating: Pfeature/Pfeature/Schneider-Wrede.csv
  inflating: Pfeature/Pfeature/data
  inflating: Pfeature/Pfeature/aaind.txt
   creating: Pfeature/build/lib/Pfeature/
  inflating: Pfeature/build/lib/Pfeature/bonds.csv
  inflating: Pfeature/build/lib/Pfeature/pfeature.py
  inflating: Pfeature/build/lib/Pfeature/AAIndexNames.csv
  inflating: Pfeature/build/lib/Pfeature/aaindices.csv
  inflating: Pfeature/build/lib/Pfeature/atom.csv
  inflating: Pfeature/build/lib/Pfeature/PhysicoChemical.csv
  inflating: Pfeature/build/lib/Pfeature/__init__.py
  inflating: __MACOSX/Pfeature/build/lib/Pfeature/.___init__.py
  inflating: Pfeature/build/lib/Pfeature/z_aaindex.csv
  inflating: Pfeature/build/lib/Pfeature/aaindex.csv
  inflating: Pfeature/build/lib/Pfeature/bin_di.csv
  inflating: Pfeature/build/lib/Pfeature/Grantham.csv
  inflating: Pfeature/build/lib/Pfeature/can_pat.csv
  inflating: Pfeature/build/lib/Pfeature/aa_attr_group.csv
  inflating: Pfeature/build/lib/Pfeature/Schneider-Wrede.csv
  inflating: Pfeature/build/lib/Pfeature/data
  inflating: Pfeature/build/lib/Pfeature/aaind.txt

In [ ]:
% cd Pfeature

/content/Pfeature/Pfeature

In [ ]:
! python setup.py install

/usr/local/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
running install
running build
running build_py
copying Pfeature/__init__.py -> build/lib/Pfeature
copying Pfeature/pfeature.py -> build/lib/Pfeature
running install_lib
creating /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/aaind.txt -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/z_aaindex.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/bin_di.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/AAIndexNames.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/bonds.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/aaindex.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/can_pat.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/__init__.py -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/aa_attr_group.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/pfeature.py -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/atom.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/Grantham.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/PhysicoChemical.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/Schneider-Wrede.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/data -> /usr/local/lib/python3.9/site-packages/Pfeature
copying build/lib/Pfeature/aaindices.csv -> /usr/local/lib/python3.9/site-packages/Pfeature
byte-compiling /usr/local/lib/python3.9/site-packages/Pfeature/__init__.py to __init__.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/Pfeature/pfeature.py to pfeature.cpython-39.pyc
running install_egg_info
Writing /usr/local/lib/python3.9/site-packages/Pfeature-1.0-py3.9.egg-info

**INSTALLING CD-HIT**

In [ ]:
! conda install -c bioconda cd-hit -y

Collecting package metadata (current_repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / done
Solving environment: \ | / done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - cd-hit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.4.26  |       h06a4308_0         124 KB
    cd-hit-4.8.1               |       hdbcaa40_0         221 KB  bioconda
    certifi-2022.6.15          |   py39h06a4308_0         153 KB
    conda-4.13.0               |   py39h06a4308_0         895 KB
    openssl-1.1.1q             |       h7f8727e_0         2.5 MB
    ------------------------------------------------------------
                                           Total:         3.9 MB

The following NEW packages will be INSTALLED:

  cd-hit             bioconda/linux-64::cd-hit-4.8.1-hdbcaa40_0

The following packages will be UPDATED:

  ca-certificates                      2020.12.8-h06a4308_0 --> 2022.4.26-h06a4308_0
  certifi                          2020.12.5-py39h06a4308_0 --> 2022.6.15-py39h06a4308_0
  conda                                4.9.2-py39h06a4308_0 --> 4.13.0-py39h06a4308_0
  openssl                                 1.1.1i-h27cfd23_0 --> 1.1.1q-h7f8727e_0



Downloading and Extracting Packages
cd-hit-4.8.1         | 221 KB    | : 100% 1.0/1 [00:00<00:00,  4.18it/s]
conda-4.13.0         | 895 KB    | : 100% 1.0/1 [00:00<00:00,  4.46it/s]
ca-certificates-2022 | 124 KB    | : 100% 1.0/1 [00:00<00:00, 17.27it/s]
openssl-1.1.1q       | 2.5 MB    | : 100% 1.0/1 [00:00<00:00,  7.10it/s]
certifi-2022.6.15    | 153 KB    | : 100% 1.0/1 [00:00<00:00, 12.09it/s]
Preparing transaction: \ done
Verifying transaction: / - done
Executing transaction: | done

In [ ]:
! conda install cvxopt

**LOAD PEPTIDE DATABASE**

In [ ]:
pip install biopython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting biopython
  Downloading biopython-1.79-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 5.1 MB/s
Collecting numpy
  Downloading numpy-1.23.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     |████████████████████████████████| 17.1 MB 571 kB/s
Installing collected packages: numpy, biopython
Successfully installed biopython-1.79 numpy-1.23.1

In [ ]:
! cat "/content/Breast_fasta.fasta"

>L6A/L17A
KWKSFAKTFKSAKKTVAHTALKAISS
>L17A/L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L17A
KWKSFLKTFKSAKKTVAHTALKAISS
>L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L6A
KWKSFAKTFKSAKKTVLHTALKAISS
>P
KWKSFLKTFKSAKKTVLHTALKAISS
>A12L
KWKSFLKTFKSLKKTVLHTALKAISS
>A20L
KWKSFLKTFKSAKKTVLHTLLKAISS
>A12L/A20L
KWKSFLKTFKSLKKTVLHTLLKAISS
>A12L/A20L/A23L
KWKSFLKTFKSLKKTVLHTLLKLISS
>Temporin-La
LLRHVVKILEKYL
>Temporin-Las
LLRHVVKILSKYL
>RGD-La
RGDLLRHVVKILEKYL
>RGD-Las
RGDLLRHVVKILSKYL
>Hecate Ac
FALALKALKKALKKLKKALKKAL
>Hecate AM
FALALKALKKALKKLKKALKKAL
>SB-37 AC
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SB-37 AM
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SHIVA 10 AC
FAKKLAKKLKKLAKKLAKLALAL
>FLAK01 AM
FALAAKALKKLAKKLKKLAKKAL
>FLAK03 AM
FALALKALKKLLKKLKKLAKKAL
>FLAK04 AM
FALALKALKKLAKKLKKLAKKAL
>FLAK05 AM
FALAKLAKKAKAKLKKALKAL
>FLAK06 AM
FALALKALKKLKKALKKAL
>FLAK06 AC
FALALKALKKLKKALKKAL
>FLAK06 R-AC
FAKKLAKKLKKLAKLALAL
>KAL V
VALALKALKKALKKLKKALKKAL
>FLAK 17 AM
FALALKKALKALKKAL
>FLAK 26 AM
FAKKLAKLAKKLAKLAL
>FLAK 25 AM
FAKKLAKLAKKLAKLALAL
>HECATE 2DAc
FALALKALKKALkkLKKALKKAL
>FLAK43 AM
FAKKLAKLAKKLLAL
>FLAK44 AM
FAKKLAKLAKKALAL
>FLAK62 AM
FALAKKALKKAKKAL
>FLAK 06R-AM
FAKKLAKKLKKLAKLALAK
>MSI-78 AM
GIGKFLKKAKKFGKAFVKILKK
>FLAK50
FAKLLAKLAKKLL
>FLAK51
FAKKLAKLALKLAKL
>FLAK57
FAKKLAKKLAKLAL
>FLAK71
FAKKLKKLAKLAKKL
>FLAK77
FAKKALKALKKL
>FLAK50V
VAKLLAKLAKKLL
>FLAK50F
FAKLLAKLAKKL
>FLAK26V AM
VAKKLAKLAKKLAKLAL
>CAME-15
KWKLFKKIGAVLKVL
>FLAK50C
FAKLLAKLAKKAL
>FLAK50D
FAKLLAKALKKLL
>FLAK 50E
FAKLLKLAAKKLL
>FLAK80
FAKLLAKKLL
>FLAK81
FAKKLAKALL
>FLAK82
FAKKLAKKLL
>FLAK83M
FAKLAKKLL
>FLAK 26 Ac
FAKKLAKLAKKLAKLAL
>Indolicidin
ILPWKWPWWPWRR
>FLAK 17 C
FAKALKALLKALKAL
>FLAK 50H
FAKLLAKLAKAKL
>FLAK 50G
FAKLLAKLAKLKL
>SHIVA DERIV P69 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>Shiva 10(1-18 AC)
FAKKLAKKLKKLAKKLAK
>SHIVA 10 PEPTIDE 71 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>CA (1-7) Shiva10 (1-16)
KWKLFKKKTKLFKKFAKKLAKKL
>FLAK 54
FAKKLAKKLAKAL
>FLAK 56
FAKKLAKKLAKLL
>FLAK 58
FAKKLAKKLAKAAL
>FLAK 72
FAKKLAKKAKLAKKL
>FLAK 75
FAKKLKKLAKKL
>SHIVA 10 (1-16) Ac
KTKLFKKFAKKLAKKLKKLAKKL
>CA(1-7) Shiva10(1-16)-COOH
KWKLFKKKTKLFKKFAKKLAKKL
>Indolocidin-ac
ILPWKWPWWPWRR
>FLAK50B
FAKALAKLAKKLL
>FLAK50I
FAKLLALALKLKL
>FLAK50K
FAKLLAKLAKAKA
>FLAK50L
FAKLLAKLAKAKG
>Shiva-11
FAKKLAKKLKKLAKKLAKLALALKALALKAL
>SHIVA 11[(1-16)ME(2-9]-COOH
FAKKLAKKLKKLAKKLIGAVLKV
>FLAK 50N
FAKLLAKALKLKL
>FLAK 50O
FAKLLAKALKKAL
>FLAK 50P
FAKLLAKALKKL
>CA(1-& HECATE(11/23)
KWKLFKKALKKLKKALKKAL
>PYL-ME
KIAKVALAKLGIGAVLKVLTTGL
>FLAG26-D1
FAKKLAKLAKKL
>VISHNU3
MPKEKVFLKIEKMGRNIRN
>MELITTIIN
GIGAVLKVLTTGLPALISWIKRKRQQ
>FLAK26-D2
FAKKLAKLAKKLAKAL
>FLAG26-D3
FAKKLLAKALKL
>FLAK50 Q1
FAKFLAKFLKKAL
>FLAK50 Q2
FAKLLFKALKKAL
>FLAK50 Q3
FAKLLAKFLKKAL
>FLAK50 Q4
FAKLLAKAFKKAL
>FLAK50 Q5
FAKLFAKAFKKAL
>FLAK50 Q6
FAKLLAKALKKFL
>FLAK50 Q7
FAKLLAKALKKFAL
>FLAK50 Q8
FAKLLAKLAKKFAL
>FLAK50 Q9
FAKLFAKLAKKFAL
>FLAK50 Q10
FKLAFKLAKKAFL
>FLAK50 T1
FAKLLAKLAK
>FLAK50 T2
FAKLLAKLAKKVL
>FLAK50 T3
FAKLLAKLAKKIL
>FLAK50 T4
FAKLLAKLAKKEL
>FLAK50 T5
FAKLLAKLAKKSL

In [ ]:
infile = open("/content/Breast_fasta.fasta")
for line in infile:
    print(line)

>L6A/L17A

KWKSFAKTFKSAKKTVAHTALKAISS

>L17A/L21A

KWKSFLKTFKSAKKTVAHTAAKAISS

>L17A

KWKSFLKTFKSAKKTVAHTALKAISS

>L21A

KWKSFLKTFKSAKKTVAHTAAKAISS

>L6A

KWKSFAKTFKSAKKTVLHTALKAISS

>P

KWKSFLKTFKSAKKTVLHTALKAISS

>A12L

KWKSFLKTFKSLKKTVLHTALKAISS

>A20L

KWKSFLKTFKSAKKTVLHTLLKAISS

>A12L/A20L

KWKSFLKTFKSLKKTVLHTLLKAISS

>A12L/A20L/A23L

KWKSFLKTFKSLKKTVLHTLLKLISS

>Temporin-La

LLRHVVKILEKYL

>Temporin-Las

LLRHVVKILSKYL

>RGD-La

RGDLLRHVVKILEKYL

>RGD-Las

RGDLLRHVVKILSKYL

>Hecate Ac

FALALKALKKALKKLKKALKKAL

>Hecate AM

FALALKALKKALKKLKKALKKAL

>SB-37 AC

MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG

>SB-37 AM

MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG

>SHIVA 10 AC

FAKKLAKKLKKLAKKLAKLALAL

>FLAK01 AM

FALAAKALKKLAKKLKKLAKKAL

>FLAK03 AM

FALALKALKKLLKKLKKLAKKAL

>FLAK04 AM

FALALKALKKLAKKLKKLAKKAL

>FLAK05 AM

FALAKLAKKAKAKLKKALKAL

>FLAK06 AM

FALALKALKKLKKALKKAL

>FLAK06 AC

FALALKALKKLKKALKKAL

>FLAK06 R-AC

FAKKLAKKLKKLAKLALAL

>KAL V

VALALKALKKALKKLKKALKKAL

>FLAK 17 AM

FALALKKALKALKKAL

>FLAK 26 AM

FAKKLAKLAKKLAKLAL

>FLAK 25 AM

FAKKLAKLAKKLAKLALAL

>HECATE 2DAc

FALALKALKKALkkLKKALKKAL

>FLAK43 AM

FAKKLAKLAKKLLAL

>FLAK44 AM

FAKKLAKLAKKALAL

>FLAK62 AM

FALAKKALKKAKKAL

>FLAK 06R-AM

FAKKLAKKLKKLAKLALAK

>MSI-78 AM

GIGKFLKKAKKFGKAFVKILKK

>FLAK50

FAKLLAKLAKKLL

>FLAK51

FAKKLAKLALKLAKL

>FLAK57

FAKKLAKKLAKLAL

>FLAK71

FAKKLKKLAKLAKKL

>FLAK77

FAKKALKALKKL

>FLAK50V

VAKLLAKLAKKLL

>FLAK50F

FAKLLAKLAKKL

>FLAK26V AM

VAKKLAKLAKKLAKLAL

>CAME-15

KWKLFKKIGAVLKVL

>FLAK50C

FAKLLAKLAKKAL

>FLAK50D

FAKLLAKALKKLL

>FLAK 50E

FAKLLKLAAKKLL

>FLAK80

FAKLLAKKLL

>FLAK81

FAKKLAKALL

>FLAK82

FAKKLAKKLL

>FLAK83M

FAKLAKKLL

>FLAK 26 Ac

FAKKLAKLAKKLAKLAL

>Indolicidin

ILPWKWPWWPWRR

>FLAK 17 C

FAKALKALLKALKAL

>FLAK 50H

FAKLLAKLAKAKL

>FLAK 50G

FAKLLAKLAKLKL

>SHIVA DERIV P69 + KWKL

FAKKLAKKLKKLAKKLAKKWKL

>Shiva 10(1-18 AC)

FAKKLAKKLKKLAKKLAK

>SHIVA 10 PEPTIDE 71 + KWKL

FAKKLAKKLKKLAKKLAKKWKL

>CA (1-7) Shiva10 (1-16)

KWKLFKKKTKLFKKFAKKLAKKL

>FLAK 54

FAKKLAKKLAKAL

>FLAK 56

FAKKLAKKLAKLL

>FLAK 58

FAKKLAKKLAKAAL

>FLAK 72

FAKKLAKKAKLAKKL

>FLAK 75

FAKKLKKLAKKL

>SHIVA 10 (1-16) Ac

KTKLFKKFAKKLAKKLKKLAKKL

>CA(1-7) Shiva10(1-16)-COOH

KWKLFKKKTKLFKKFAKKLAKKL

>Indolocidin-ac

ILPWKWPWWPWRR

>FLAK50B

FAKALAKLAKKLL

>FLAK50I

FAKLLALALKLKL

>FLAK50K

FAKLLAKLAKAKA

>FLAK50L

FAKLLAKLAKAKG

>Shiva-11

FAKKLAKKLKKLAKKLAKLALALKALALKAL

>SHIVA 11[(1-16)ME(2-9]-COOH

FAKKLAKKLKKLAKKLIGAVLKV

>FLAK 50N

FAKLLAKALKLKL

>FLAK 50O

FAKLLAKALKKAL

>FLAK 50P

FAKLLAKALKKL

>CA(1-& HECATE(11/23)

KWKLFKKALKKLKKALKKAL

>PYL-ME

KIAKVALAKLGIGAVLKVLTTGL

>FLAG26-D1

FAKKLAKLAKKL

>VISHNU3

MPKEKVFLKIEKMGRNIRN

>MELITTIIN

GIGAVLKVLTTGLPALISWIKRKRQQ

>FLAK26-D2

FAKKLAKLAKKLAKAL

>FLAG26-D3

FAKKLLAKALKL

>FLAK50 Q1

FAKFLAKFLKKAL

>FLAK50 Q2

FAKLLFKALKKAL

>FLAK50 Q3

FAKLLAKFLKKAL

>FLAK50 Q4

FAKLLAKAFKKAL

>FLAK50 Q5

FAKLFAKAFKKAL

>FLAK50 Q6

FAKLLAKALKKFL

>FLAK50 Q7

FAKLLAKALKKFAL

>FLAK50 Q8

FAKLLAKLAKKFAL

>FLAK50 Q9

FAKLFAKLAKKFAL

>FLAK50 Q10

FKLAFKLAKKAFL

>FLAK50 T1

FAKLLAKLAK

>FLAK50 T2

FAKLLAKLAKKVL

>FLAK50 T3

FAKLLAKLAKKIL

>FLAK50 T4

FAKLLAKLAKKEL

>FLAK50 T5

FAKLLAKLAKKSL

In [ ]:
#combining Data
! cat /content/Breast_fasta.fasta /content/Cervix_fasta.fasta /content/Colon_fasta.fasta /content/Lungs_fasta.fasta /content/Prostate_fasta.fasta /content/skin_fasta.fasta > Positive_Combined.fasta

! cat "Positive_Combined.fasta"

>L6A/L17A
KWKSFAKTFKSAKKTVAHTALKAISS
>L17A/L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L17A
KWKSFLKTFKSAKKTVAHTALKAISS
>L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L6A
KWKSFAKTFKSAKKTVLHTALKAISS
>P
KWKSFLKTFKSAKKTVLHTALKAISS
>A12L
KWKSFLKTFKSLKKTVLHTALKAISS
>A20L
KWKSFLKTFKSAKKTVLHTLLKAISS
>A12L/A20L
KWKSFLKTFKSLKKTVLHTLLKAISS
>A12L/A20L/A23L
KWKSFLKTFKSLKKTVLHTLLKLISS
>Temporin-La
LLRHVVKILEKYL
>Temporin-Las
LLRHVVKILSKYL
>RGD-La
RGDLLRHVVKILEKYL
>RGD-Las
RGDLLRHVVKILSKYL
>Hecate Ac
FALALKALKKALKKLKKALKKAL
>Hecate AM
FALALKALKKALKKLKKALKKAL
>SB-37 AC
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SB-37 AM
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SHIVA 10 AC
FAKKLAKKLKKLAKKLAKLALAL
>FLAK01 AM
FALAAKALKKLAKKLKKLAKKAL
>FLAK03 AM
FALALKALKKLLKKLKKLAKKAL
>FLAK04 AM
FALALKALKKLAKKLKKLAKKAL
>FLAK05 AM
FALAKLAKKAKAKLKKALKAL
>FLAK06 AM
FALALKALKKLKKALKKAL
>FLAK06 AC
FALALKALKKLKKALKKAL
>FLAK06 R-AC
FAKKLAKKLKKLAKLALAL
>KAL V
VALALKALKKALKKLKKALKKAL
>FLAK 17 AM
FALALKKALKALKKAL
>FLAK 26 AM
FAKKLAKLAKKLAKLAL
>FLAK 25 AM
FAKKLAKLAKKLAKLALAL
>HECATE 2DAc
FALALKALKKALkkLKKALKKAL
>FLAK43 AM
FAKKLAKLAKKLLAL
>FLAK44 AM
FAKKLAKLAKKALAL
>FLAK62 AM
FALAKKALKKAKKAL
>FLAK 06R-AM
FAKKLAKKLKKLAKLALAK
>MSI-78 AM
GIGKFLKKAKKFGKAFVKILKK
>FLAK50
FAKLLAKLAKKLL
>FLAK51
FAKKLAKLALKLAKL
>FLAK57
FAKKLAKKLAKLAL
>FLAK71
FAKKLKKLAKLAKKL
>FLAK77
FAKKALKALKKL
>FLAK50V
VAKLLAKLAKKLL
>FLAK50F
FAKLLAKLAKKL
>FLAK26V AM
VAKKLAKLAKKLAKLAL
>CAME-15
KWKLFKKIGAVLKVL
>FLAK50C
FAKLLAKLAKKAL
>FLAK50D
FAKLLAKALKKLL
>FLAK 50E
FAKLLKLAAKKLL
>FLAK80
FAKLLAKKLL
>FLAK81
FAKKLAKALL
>FLAK82
FAKKLAKKLL
>FLAK83M
FAKLAKKLL
>FLAK 26 Ac
FAKKLAKLAKKLAKLAL
>Indolicidin
ILPWKWPWWPWRR
>FLAK 17 C
FAKALKALLKALKAL
>FLAK 50H
FAKLLAKLAKAKL
>FLAK 50G
FAKLLAKLAKLKL
>SHIVA DERIV P69 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>Shiva 10(1-18 AC)
FAKKLAKKLKKLAKKLAK
>SHIVA 10 PEPTIDE 71 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>CA (1-7) Shiva10 (1-16)
KWKLFKKKTKLFKKFAKKLAKKL
>FLAK 54
FAKKLAKKLAKAL
>FLAK 56
FAKKLAKKLAKLL
>FLAK 58
FAKKLAKKLAKAAL
>FLAK 72
FAKKLAKKAKLAKKL
>FLAK 75
FAKKLKKLAKKL
>SHIVA 10 (1-16) Ac
KTKLFKKFAKKLAKKLKKLAKKL
>CA(1-7) Shiva10(1-16)-COOH
KWKLFKKKTKLFKKFAKKLAKKL
>Indolocidin-ac
ILPWKWPWWPWRR
>FLAK50B
FAKALAKLAKKLL
>FLAK50I
FAKLLALALKLKL
>FLAK50K
FAKLLAKLAKAKA
>FLAK50L
FAKLLAKLAKAKG
>Shiva-11
FAKKLAKKLKKLAKKLAKLALALKALALKAL
>SHIVA 11[(1-16)ME(2-9]-COOH
FAKKLAKKLKKLAKKLIGAVLKV
>FLAK 50N
FAKLLAKALKLKL
>FLAK 50O
FAKLLAKALKKAL
>FLAK 50P
FAKLLAKALKKL
>CA(1-& HECATE(11/23)
KWKLFKKALKKLKKALKKAL
>PYL-ME
KIAKVALAKLGIGAVLKVLTTGL
>FLAG26-D1
FAKKLAKLAKKL
>VISHNU3
MPKEKVFLKIEKMGRNIRN
>MELITTIIN
GIGAVLKVLTTGLPALISWIKRKRQQ
>FLAK26-D2
FAKKLAKLAKKLAKAL
>FLAG26-D3
FAKKLLAKALKL
>FLAK50 Q1
FAKFLAKFLKKAL
>FLAK50 Q2
FAKLLFKALKKAL
>FLAK50 Q3
FAKLLAKFLKKAL
>FLAK50 Q4
FAKLLAKAFKKAL
>FLAK50 Q5
FAKLFAKAFKKAL
>FLAK50 Q6
FAKLLAKALKKFL
>FLAK50 Q7
FAKLLAKALKKFAL
>FLAK50 Q8
FAKLLAKLAKKFAL
>FLAK50 Q9
FAKLFAKLAKKFAL
>FLAK50 Q10
FKLAFKLAKKAFL
>FLAK50 T1
FAKLLAKLAK
>FLAK50 T2
FAKLLAKLAKKVL
>FLAK50 T3
FAKLLAKLAKKIL
>FLAK50 T4
FAKLLAKLAKKEL
>FLAK50 T5
FAKLLAKLAKKSL
>Cationic Amphiphilic
GIIKKIIIKKI
>Cationic Amphiphilic
GIIKKIIIKKIIIKKI
>L6A/L17A
KWKSFAKTFKSAKKTVAHTALKAISS
>L17A/L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L17A
KWKSFLKTFKSAKKTVAHTALKAISS
>L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L6A
KWKSFAKTFKSAKKTVLHTALKAISS
>P
KWKSFLKTFKSAKKTVLHTALKAISS
>A12L
KWKSFLKTFKSLKKTVLHTALKAISS
>A20L
KWKSFLKTFKSAKKTVLHTLLKAISS
>A12L/A20L
KWKSFLKTFKSLKKTVLHTLLKAISS
>A12L/A20L/A23L
KWKSFLKTFKSLKKTVLHTLLKLISS
>Temporin-La
LLRHVVKILEKYL
>Temporin-Las
LLRHVVKILSKYL
>RGD-La
RGDLLRHVVKILEKYL
>RGD-Las
RGDLLRHVVKILSKYL
>Hecate AC
FALALKALKKALKKLKKALKKAL
>Hecate AM
FALALKALKKALKKLKKALKKAL
>SB-37 AC
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SB-37 AM
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SHIVA 10 AC
FAKKLAKKLKKLAKKLAKLALAL
>FLAK01 AM
FALAAKALKKLAKKLKKLAKKAL
>FLAK03 AM
FALALKALKKLLKKLKKLAKKAL
>FLAK04 AM
FALALKALKKLAKKLKKLAKKAL
>FLAK05 AM
FALAKLAKKAKAKLKKALKAL
>FLAK06 AM
FALALKALKKLKKALKKAL
>FLAK06 AC
FALALKALKKLKKALKKAL
>FLAK06 R-AC
FAKKLAKKLKKLAKLALAL
>KAL V
VALALKALKKALKKLKKALKKAL
>FLAK 17 AM
FALALKKALKALKKAL
>FLAK 26 AM
FAKKLAKLAKKLAKLAL
>FLAK 25 AM
FAKKLAKLAKKLAKLALAL
>HECATE 2DAc
FALALKALKKALkkLKKALKKAL
>FLAK43 AM
FAKKLAKLAKKLLAL
>FLAK44 AM
FAKKLAKLAKKALAL
>FLAK62 AM
FALAKKALKKAKKAL
>FLAK 06R-AM
FAKKLAKKLKKLAKLALAK
>MSI-78 AM
GIGKFLKKAKKFGKAFVKILKK
>FLAK50
FAKLLAKLAKKLL
>FLAK51
FAKKLAKLALKLAKL
>FLAK57
FAKKLAKKLAKLAL
>FLAK71
FAKKLKKLAKLAKKL
>FLAK77
FAKKALKALKKL
>FLAK50V
VAKLLAKLAKKLL
>FLAK50F
FAKLLAKLAKKL
>FLAK26V AM
VAKKLAKLAKKLAKLAL
>CAME-15
KWKLFKKIGAVLKVL
>CAME-15
KWKLFKKIGAVLKVL
>FLAK50D
FAKLLAKALKKLL
>FLAK 50E
FAKLLKLAAKKLL
>FLAK80
FAKLLAKKLL
>FLAK81
FAKKLAKALL
>FLAK82
FAKKLAKKLL
>FLAK83M
FAKLAKKLL
>FLAK 26 Ac
FAKKLAKLAKKLAKLAL
>Indolicidin
ILPWKWPWWPWRR
>FLAK 50H
FAKLLAKLAKAKL
>FLAK 50G
FAKLLAKLAKLKL
>SHIVA DERIV P69 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>Shiva 10(1-18 AC)
FAKKLAKKLKKLAKKLAK
>SHIVA 10 PEPTIDE 71 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>CA(1-7) Shiva10(1-16)
KWKLFKKKTKLFKKFAKKLAKKL
>FLAK 54
FAKKLAKKLAKAL
>FLAK 56
FAKKLAKKLAKLL
>FLAK 58
FAKKLAKKLAKAAL
>FLAK 72
FAKKLAKKAKLAKKL
>FLAK 75
FAKKLKKLAKKL
>SHIVA 10 (1-16) Ac
KTKLFKKFAKKLAKKLKKLAKKL
>CA(1-7) Shiva10(1-16)-COOH
KWKLFKKKTKLFKKFAKKLAKKL
>Indolocidin-ac
ILPWKWPWWPWRR
>FLAK50B
FAKALAKLAKKLL
>FLAK50J
FAKLLAKLAKKAA
>FLAK50I
FAKLLALALKLKL
>FLAK50K
FAKLLAKLAKAKA
>FLAK50L
FAKLLAKLAKAKG
>Shiva-11
FAKKLAKKLKKLAKKLAKLALALKALALKAL
>SHIVA 11[(1-16)ME(2-9]-COOH
FAKKLAKKLKKLAKKLIGAVLKV
>FLAK 50N
FAKLLAKALKLKL
>FLAK 50O
FAKLLAKALKKAL
>FLAK 50P
FAKLLAKALKKL
>CA(1-& HECATE(11/23)
KWKLFKKALKKLKKALKKAL
>PYL-ME
KIAKVALAKLGIGAVLKVLTTGL
>FLAG26-D1
FAKKLAKLAKKL
>VISHNU3
MPKEKVFLKIEKMGRNIRN
>MELITTIIN
GIGAVLKVLTTGLPALISWIKRKRQQ
>FLAK26-D2
FAKKLAKLAKKLAKAL
>FLAG26-D3
FAKKLLAKALKL
>FLAK50 Q1
FAKFLAKFLKKAL
>FLAK50 Q2
FAKLLFKALKKAL
>FLAK50 Q3
FAKLLAKFLKKAL
>FLAK50 Q5
FAKLFAKAFKKAL
>FLAK50 Q6
FAKLLAKALKKFL
>FLAK50 Q7
FAKLLAKALKKFAL
>FLAK50 Q8
FAKLLAKLAKKFAL
>FLAK50 Q9
FAKLFAKLAKKFAL
>FLAK50 Q10
FKLAFKLAKKAFL
>FLAK50 T1
FAKLLAKLAK
>FLAK50 T2
AKLLAKLAKKVL
>Epinecidin-8
FIFHIIKGLFHAGKMI
>Epinecidin-8
FIFHIIKGLFHAGKMI
>L6A/L17A
KWKSFAKTFKSAKKTVAHTALKAISS
>L17A/L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L17A
KWKSFLKTFKSAKKTVAHTALKAISS
>L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L6A
KWKSFAKTFKSAKKTVLHTALKAISS
>P
KWKSFLKTFKSAKKTVLHTALKAISS
>A12L
KWKSFLKTFKSLKKTVLHTALKAISS
>A20L
KWKSFLKTFKSAKKTVLHTLLKAISS
>A12L/A20L
KWKSFLKTFKSLKKTVLHTLLKAISS
>A12L/A20L/A23L
KWKSFLKTFKSLKKTVLHTLLKLISS
>A5
KAQIRAMECNIL
>Tat
RKKRRQRRR
>Tat-a5
KAQIRAMECNILGRKKRRQRRR
>Temporin-La
LLRHVVKILEKYL
>Temporin-Las
LLRHVVKILSKYL
>RGD-La
RGDLLRHVVKILEKYL
>RGD-Las
RGDLLRHVVKILSKYL
>Hecate AC
FALALKALKKALKKLKKALKKAL
>Hecate AM
FALALKALKKALKKLKKALKKAL
>SB-37 AC
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SB-37 AM
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SHIVA 10 AC
FAKKLAKKLKKLAKKLAKLALAL
>FLAK01 AM
FALAAKALKKLAKKLKKLAKKAL
>FLAK03 AM
FALALKALKKLLKKLKKLAKKAL
>FLAK04 AM
FALALKALKKLAKKLKKLAKKAL
>FLAK05 AM
FALAKLAKKAKAKLKKALKAL
>FLAK06 AM
FALALKALKKLKKALKKAL
>FLAK06 AC
FALALKALKKLKKALKKAL
>FLAK06 R-AC
FAKKLAKKLKKLAKLALAL
>KAL V
VALALKALKKALKKLKKALKKAL
>FLAK 17 AM
FALALKKALKALKKAL
>FLAK 26 AM
FAKKLAKLAKKLAKLAL
>FLAK 25 AM
FAKKLAKLAKKLAKLALAL
>HECATE 2DAc
FALALKALKKALkkLKKALKKAL
>FLAK43 AM
FAKKLAKLAKKLLAL
>FLAK44 AM
FAKKLAKLAKKALAL
>FLAK62 AM
FALAKKALKKAKKAL
>FLAK 06R-AM
FAKKLAKKLKKLAKLALAK
>MSI-78 AM
GIGKFLKKAKKFGKAFVKILKK
>FLAK50
FAKLLAKLAKKLL
>FLAK51
FAKKLAKLALKLAKL
>FLAK57
FAKKLAKKLAKLAL
>FLAK71
FAKKLKKLAKLAKKL
>FLAK77
FAKKALKALKKL
>FLAK50V
VAKLLAKLAKKLL
>FLAK50F
FAKLLAKLAKKL
>FLAK26V AM
VAKKLAKLAKKLAKLAL
>CAME-15
KWKLFKKIGAVLKVL
>FLAK50C
FAKLLAKLAKKAL
>FLAK50D
FAKLLAKALKKLL
>FLAK 50E
FAKLLKLAAKKLL
>FLAK80
FAKLLAKKLL
>FLAK81
FAKKLAKALL
>FLAK82
FAKKLAKKLL
>FLAK83M
FAKLAKKLL
>FLAK 26 Ac
FAKKLAKLAKKLAKLAL
>Indolicidin
ILPWKWPWWPWRR
>FLAK 17 C
FAKALKALLKALKAL
>FLAK 50H
FAKLLAKLAKAKL
>FLAK 50G
FAKLLAKLAKLKL
>SHIVA DERIV P69 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>Shiva 10(1-18 AC)
FAKKLAKKLKKLAKKLAK
>SHIVA 10 PEPTIDE 71 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>CA(1-7) Shiva10(1-16)
KWKLFKKKTKLFKKFAKKLAKKL
>FLAK 54
FAKKLAKKLAKAL
>FLAK 56
FAKKLAKKLAKLL
>FLAK 58
FAKKLAKKLAKAAL
>FLAK 72
FAKKLAKKAKLAKKL
>FLAK 75
FAKKLKKLAKKL
>SHIVA 10 (1-16) Ac
KTKLFKKFAKKLAKKLKKLAKKL
>CA(1-7) Shiva10(1-16)-COOH
KWKLFKKKTKLFKKFAKKLAKKL
>Indolocidin-ac
ILPWKWPWWPWRR
>FLAK50B
FAKALAKLAKKLL
>FLAK50I
FAKLLALALKLKL
>FLAK50K
FAKLLAKLAKAKA
>FLAK50L
FAKLLAKLAKAKG
>Shiva-11
FAKKLAKKLKKLAKKLAKLALALKALALKAL
>SHIVA 11[(1-16)ME(2-9]-COOH
FAKKLAKKLKKLAKKLIGAVLKV
>FLAK 50N
FAKLLAKALKLKL
>FLAK 50O
FAKLLAKALKKAL
>FLAK 50P
FAKLLAKALKKL
>CA(1-& HECATE(11/23)
KWKLFKKALKKLKKALKKAL
>PYL-ME
KIAKVALAKLGIGAVLKVLTTGL
>FLAG26-D1
FAKKLAKLAKKL
>VISHNU3
MPKEKVFLKIEKMGRNIRN
>MELITTIIN
GIGAVLKVLTTGLPALISWIKRKRQQ
>FLAK26-D2
FAKKLAKLAKKLAKAL
>FLAG26-D3
FAKKLLAKALKL
>FLAK50 Q1
FAKFLAKFLKKAL
>FLAK50 Q2
FAKLLFKALKKAL
>FLAK50 Q3
FAKLLAKFLKKAL
>FLAK50 Q4
FAKLLAKAFKKAL
>FLAK50 Q5
FAKLFAKAFKKAL
>FLAK50 Q6
FAKLLAKALKKFL
>FLAK50 Q7
FAKLLAKALKKFAL
>FLAK50 Q8
FAKLLAKLAKKFAL
>FLAK50 Q9
FAKLFAKLAKKFAL
>FLAK50 Q10
FKLAFKLAKKAFL
>FLAK50 T1
FAKLLAKLAK
>FLAK50 T2
FAKLLAKLAKKVL
>L6A/L17A
KWKSFAKTFKSAKKTVAHTALKAISS
>L17A/L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L17A
KWKSFLKTFKSAKKTVAHTALKAISS
>L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L6A
KWKSFAKTFKSAKKTVLHTALKAISS
>P
KWKSFLKTFKSAKKTVLHTALKAISS
>A12L
KWKSFLKTFKSLKKTVLHTALKAISS
>A20L
KWKSFLKTFKSAKKTVLHTLLKAISS
>A12L/A20L
KWKSFLKTFKSLKKTVLHTLLKAISS
>A12L/A20L/A23L
KWKSFLKTFKSLKKTVLHTLLKLISS
>L6A/L17A
KWKSFAKTFKSAKKTVAHTALKAISS
>L17A/L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L17A
KWKSFLKTFKSAKKTVAHTALKAISS
>L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>L6A
KWKSFAKTFKSAKKTVLHTALKAISS
>P
KWKSFLKTFKSAKKTVLHTALKAISS
>A12L
KWKSFLKTFKSLKKTVLHTALKAISS
>A20L
KWKSFLKTFKSAKKTVLHTLLKAISS
>A12L/A20L
KWKSFLKTFKSLKKTVLHTLLKAISS
>A12L/A20L/A23L
KWKSFLKTFKSLKKTVLHTLLKLISS
>Temporin-La
LLRHVVKILEKYL
>Temporin-Las
LLRHVVKILSKYL
>RGD-La
RGDLLRHVVKILEKYL
>RGD-Las
RGDLLRHVVKILSKYL
>Hecate AC
FALALKALKKALKKLKKALKKAL
>Hecate AM
FALALKALKKALKKLKKALKKAL
>SB-37 AC
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SB-37 AM
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SHIVA 10 AC
FAKKLAKKLKKLAKKLAKLALAL
>FLAK01 AM
FALAAKALKKLAKKLKKLAKKAL
>FLAK03 AM
FALALKALKKLLKKLKKLAKKAL
>FLAK04 AM
FALALKALKKLAKKLKKLAKKAL
>FLAK05 AM
FALAKLAKKAKAKLKKALKAL
>FLAK06 AM
FALALKALKKLKKALKKAL
>FLAK06 AC
FALALKALKKLKKALKKAL
>FLAK06 AM
FAKKLAKKLKKLAKLALAL
>KAL V
VALALKALKKALKKLKKALKKAL
>FLAK 17 AMV
FALALKKALKALKKAL
>FLAK 26 AM
FAKKLAKLAKKLAKLAL
>FLAK 25 AM
FAKKLAKLAKKLAKLALAL
>HECATE 2DAc
FALALKALKKALkkLKKALKKAL
>FLAK43 AM
FAKKLAKLAKKLLAL
>FLAK44 AM
FAKKLAKLAKKALAL
>FLAK62 AM
FALAKKALKKAKKAL
>FLAK 06R-AM
FAKKLAKKLKKLAKLALAK
>MSI-78 AM
GIGKFLKKAKKFGKAFVKILKK
>FLAK50
FAKLLAKLAKKLL
>FLAK51
FAKKLAKLALKLAKL
>FLAK57
FAKKLAKKLAKLAL
>FLAK71
FAKKLKKLAKLAKKL
>FLAK77
FAKKALKALKKL
>FLAK50V
VAKLLAKLAKKLL
>FLAK50F
FAKLLAKLAKKL
>FLAK26V AM
VAKKLAKLAKKLAKLAL
>CAME-15
KWKLFKKIGAVLKVL
>FLAK50C
FAKLLAKLAKKAL
>FLAK50D
FAKLLAKALKKLL
>FLAK 50E
FAKLLKLAAKKLL
>FLAK80
FAKLLAKKLL
>FLAK81
FAKKLAKALL
>FLAK82
FAKKLAKKLL
>FLAK83M
FAKLAKKLL
>FLAK 26 Ac
FAKKLAKLAKKLAKLAL
>Indolicidin
ILPWKWPWWPWRR
>FLAK 17 C
FAKALKALLKALKAL
>FLAK 50H
FAKLLAKLAKAKL
>FLAK 50G
FAKLLAKLAKLKL
>SHIVA DERIV P69 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>Shiva 10(1-18 AC)
FAKKLAKKLKKLAKKLAK
>SHIVA 10 PEPTIDE 71 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>CA(1-7)Shiva10(1-16)
KWKLFKKKTKLFKKFAKKLAKKL
>FLAK 54
FAKKLAKKLAKAL
>FLAK 56
FAKKLAKKLAKLL
>FLAK 58
FAKKLAKKLAKAAL
>FLAK 72
FAKKLAKKAKLAKKL
>FLAK 75
FAKKLKKLAKKL
>SHIVA 10 (1-16)
KTKLFKKFAKKLAKKLKKLAKKL
>CA(1-7) Shiva10(1-16)
KWKLFKKKTKLFKKFAKKLAKKL
>Indolocidin-ac
ILPWKWPWWPWRR
>FLAK50B
FAKALAKLAKKLL
>FLAK50J
FAKLLAKLAKKAA
>FLAK50I
FAKLLALALKLKL
>FLAK50K
FAKLLAKLAKAKA
>FLAK50L
FAKLLAKLAKAKG
>Shiva-11
FAKKLAKKLKKLAKKLAKLALALKALALKAL
>SHIVA 11[(1-16)ME(2-9]-COOH
FAKKLAKKLKKLAKKLIGAVLKV
>FLAK 50N
FAKLLAKALKLKL
>FLAK 50O
FAKLLAKALKKAL
>FLAK 50P
FAKLLAKALKKL
>CA(1-& HECATE(11/23)
KWKLFKKALKKLKKALKKAL
>PYL-ME
KIAKVALAKLGIGAVLKVLTTGL
>FLAG26-D1
FAKKLAKLAKKL
>VISHNU3
MPKEKVFLKIEKMGRNIRN
>MELITTIIN
GIGAVLKVLTTGLPALISWIKRKRQQ
>FLAK26-D2
FAKKLAKLAKKLAKAL
>FLAG26-D3
FAKKLLAKALKL
>FLAK50 Q1
FAKFLAKFLKKAL
>FLAK50 Q2
FAKLLFKALKKAL
>FLAK50 Q3
FAKLLAKFLKKAL
>FLAK50 Q4
FAKLLAKAFKKAL
>EB(H2R)-lytic
YRWYGYTPQNVIGGGKLlLKlLkkLLKlLKKK
>EB-Lytic
YHWYGYTPQNVIGGGKLlLKlLkkLLKlLKKK
>FLAK50T9
YAKLLAKLAKKAL
>FLAK-120F
WALAL
>KAL V
VALALKALKKALKKLKKALKKAL
>FLAK50T8
VAKLLAKLAKKVL
>FLAK50V
VAKLLAKLAKKLL
>FLAK26V AM
VAKKLAKLAKKLAKLAL
>Transferrin receptor (TfR)-lytic hybrid peptide
THRPPMWSPVWPGGGKLlLKlLkkLLKlLKKK
>9S1R
RRRRRWCMNW
>9S1R
RRRRRWCMNW
>9S1R
RRRRRWCMNW
>9R
RRRRRNWMWC
>9R
RRRRRNWMWC
>9R
RRRRRNWMWC
>Buforin IIb
RAGLQFPVGRLLRRLLRRLLR
>Buforin IIb
RAGLQFPVGRLLRRLLRRLLR
>SB-37 AC
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SB-37 AM
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>VISHNU3
MPKEKVFLKIEKMGRNIRN
>DL6R6
lRRllRRllRRl
>LSB-37
LPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>LL 37
LLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES
>D-K6L9
LKlLKKLlkKLLkLL
>D-K6L9
LKlLKKLlkKLLkLL
>DL6K6
lKKllKKllKKl
>DDA-DL6K6-22
lKKllKKllKKl
>MA-DL6K6-23
lKKllKKllKKl
>PA-DL6K6-24
lKKllKKllKKl
>Flak 96L
LKKLAKLALAF
>FLAK98
KYKKALKKLAKLL
>Dex-(KW)3
KWKWKW
>CA(1-7)Shiva10(1-16)
KWKLFKKKTKLFKKFAKKLAKKL
>CA(1-7) Shiva10(1-16)-COOH
KWKLFKKKTKLFKKFAKKLAKKL
>CAME-15
KWKLFKKIGAVLKVL
>CA(1-& HECATE(11/23)
KWKLFKKALKKLKKALKKAL
>FLAK93
KWKLF
>FLAK93B
KWKLAKKALALL
>SHIVA 10 (1-16) Ac
KTKLFKKFAKKLAKKLKKLAKKL
>Lytik
KLlLKlLkkLLKlLKKK
>FLAK100-CO2H
KLLKLLLKLYKKLLKLL
>FLAK99
KLALKLALKALKAAKLA
>Modelin-5
KLAKKLAKLAKLAKAL
>Modelin-5-CO2H
KLAKKLAKLAKLAKAL
>KSL-1
KKVVFKVKFK
>PYL-ME
KIAKVALAKLGIGAVLKVLTTGL
>Modelin-8E
KFKKLAKKW
>Modelin-8D
KFKKLAKKF
>FLAK92
KAKLF
>FLAK92B
KAKLAKKALAKLL
>Indolicidin
ILPWKWPWWPWRR
>Indolocidin-ac
ILPWKWPWWPWRR
>Adenoregulin
GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV
>Adenoregulin
GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV
>Adenoregulin
GLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV
>22
GLFKVIKKVASVIGGL
>23
GLFKVIKKVAKVIKKL
>ltc2aG11A
GLFGKLIKKFARKAISYAVKKARGKH
>13
GLFDVIKKVASVIKKL
>11
GLFDVIKKVASVIKGL
>Citropin 1.1
GLFDVIKKVASVIGGL
>7
GLFDVIKKVAAVIGGL
>Aurein2.5
GLFDIVKKVVGAFGSL
>Aurein 3.3
GLFDIVKKIAGHIVSSI
>Aurein 3.2
GLFDIVKKIAGHIASSI
>Aurein 3.1
GLFDIVKKIAGHIAGSI
>Aurein1.2
GLFDIIKKIAESF
>Aurein2.6
GLFDIAKKVIGVIGSL
>MSI-78 AM
GIGKFLKKAKKFGKAFVKILKK
>Pexiganan
GIGKFLKKAKKFGKAFVKILKK
>Magainin 2
GIGKFLHSAKKFGKAFVGEIMNS
>Magainin G
GIGKFLHSAKKFAKAFVAEIMNS
>Magainin B
GIGKFLHAAKKFAKAFVAEIMNS
>Magainin2wisc
GIGKFLHAAKKFAKAFVAEIMNS
>MELITTIIN
GIGAVLKVLTTGLPALISWIKRKRQQ
>Gaegurin peptides SEQID NO: 4
FLWWLFKWAWK
>Gaegurin peptides SEQID NO: 4
FLWWLFKWAWK
>GA-W4
FLWWLFKWAWK
>GA-W4
FLWWLFKWAWK
>TsAP-S1
FLSLIPKLVKKIIKAFK
>Gaegurin peptides SEQID NO: 2
FLKWLFKWAKK
>Gaegurin peptides SEQID NO: 2
FLKWLFKWAKK
>GA-K4
FLKWLFKWAKK
>GA-K4
FLKWLFKWAKK
>PTP5
FLKLLKKLAAKLF
>PTP6
FLKLLKKLAAKLF
>PTP4
FLKLLKKLAAKFLPTIICKISYKC
>PTP8
FLKLLAGLLKNFA
>Gaegurin peptides SEQID NO: 3
FLGWLFKWAWK
>FLAK50
FAKLLAKLAKKLL
>FLAK50F
FAKLLAKLAKKL
>FLAK50 T3
FAKLLAKLAKKIL
>FLAK50T7
FAKLLAKLAKKGL
>FLAK50 Q8
FAKLLAKLAKKFAL
>FLAK50 T4
FAKLLAKLAKKEL
>FLAK50C
FAKLLAKLAKKAL
>FLAK50J
FAKLLAKLAKKAA
>FLAK50T6
FAKLLAKLAKK
>FLAK50L
FAKLLAKLAKAKG
>FLAK50K
FAKLLAKLAKAKA
>Z10
AAKKWAKAKWAKAKKWAKAA
>Z9
AAWKWAWAKKWAKAKKWAKAA
>Z8
AWKKWAKAWKWAKAKWWAKAA
>Peptide-20
CSSRTMHHC
>Peptide-20
CSSRTMHHC
>Peptide-20
CSSRTMHHC
>Peptide-20
CSSRTMHHC
>FLAK50 Z9
FAFAKIIAKIAKKII
>FLAK50 Z9
FAFAKIIAKIAKKII
>FLAK50 Z7
FAFGKGIGKIGKKGL
>FLAK50 Z7
FAFGKGIGKIGKKGL
>FLAK50 Z2
FAFGKGIGKVGKKLL
>FLAK50 Z2
FAFGKGIGKVGKKLL
>FLAK50 Z3
FAKAIAKIAFGKGIGKVGKKLL
>FLAK50 Z3
FAKAIAKIAFGKGIGKVGKKLL
>FLAK50B
FAKALAKLAKKLL
>FLAK50B
FAKALAKLAKKLL
>FLAK 17 C
FAKALKALLKALKAL
>FLAK 17 C
FAKALKALLKALKAL
>FLAK50 Q1
FAKFLAKFLKKAL
>FLAK50 Q1
FAKFLAKFLKKAL
>FLAK50 Z6
FAKGVGKVGKKAL
>FLAK50 Z6
FAKGVGKVGKKAL
>FLAK50 Z8
FAKIIAKIAKIAKKIL
>FLAK50 Z8
FAKIIAKIAKIAKKIL
>FLAK50 Z10
FAKIIAKIAKKI
>FLAK50 Z10
FAKIIAKIAKKI
>FLAK77
FAKKALKALKKL
>FLAK77
FAKKALKALKKL
>D2A21
FAKKFAKKFKKFAKKFAKFAFAF
>D2A21
FAKKFAKKFKKFAKKFAKFAFAF
>FLAK81
FAKKLAKALL
>FLAK81
FAKKLAKALL
>FLAK 72
FAKKLAKKAKLAKKL
>FLAK 72
FAKKLAKKAKLAKKL
>FLAK 58
FAKKLAKKLAKAAL
>FLAK 58
FAKKLAKKLAKAAL
>FLAK 54
FAKKLAKKLAKAL
>FLAK 54
FAKKLAKKLAKAL
>FLAK57
FAKKLAKKLAKLAL
>FLAK57
FAKKLAKKLAKLAL
>FLAK 56
FAKKLAKKLAKLL
>FLAK 56
FAKKLAKKLAKLL
>Shiva 10(1-18 AC)
FAKKLAKKLKKLAKKLAK
>Shiva 10(1-18 AC)
FAKKLAKKLKKLAKKLAK
>SHIVA DERIV P69 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>SHIVA 10 PEPTIDE 71 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>SHIVA DERIV P69 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>SHIVA 10 PEPTIDE 71 + KWKL
FAKKLAKKLKKLAKKLAKKWKL
>Anubis-2
FAKKLAKKLKKLAKKLAKLAKKL
>Buforin IIb
RAGLQFPVGRLLRRLLRRLLR
>Buforin IIb
RAGLQFPVGRLLRRLLRRLLR
>Buforin IIb
RAGLQFPVGRLLRRLLRRLLR
>Buforin IIb
RAGLQFPVGRLLRRLLRRLLR
>Aurein1.2
GLFDIIKKIAESF
>Aurein2.5
GLFDIVKKVVGAFGSL
>Aurein2.6
GLFDIAKKVIGVIGSL
>Aurein 3.1
GLFDIVKKIAGHIAGSI
>Aurein 3.2
GLFDIVKKIAGHIASSI
>Aurein 3.3
GLFDIVKKIAGHIVSSI
>l3,10,13K7,8K4R2L9
KLlRLLkkLlRLlLK
>l3,4,8,10K5L7
KlllKLKlKlLK
>L6A/L17A
KWKSFAKTFKSAKKTVAHTALKAISS
>L17A
KWKSFLKTFKSAKKTVAHTALKAISS
>L21A
KWKSFLKTFKSAKKTVAHTAAKAISS
>P
KWKSFLKTFKSAKKTVLHTALKAISS
>L1
PEWFKCRRWQWRMKKLGA
>L2
PAWFKARRWAWRMKKLAA
>L3
PAWRKAFRWAWRMKKLAA
>L4
PAWFKARRWAWRMLKKAA
>L9
PAWRKAARWAWRMLKKAA
>Gaegurin peptides SEQID NO: 1
FLGWLFKWAKK
>Hecate AC
FALALKALKKALKKLKKALKKAL
>SB-37 AC
MPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG
>SHIVA 10 AC
FAKKLAKKLKKLAKKLAKLALAL
>FLAK04 AM
FALALKALKKLAKKLKKLAKKAL
>FLAK06 AM
FAKKLAKKLKKLAKLALAL
>FLAK 25 AM
FAKKLAKLAKKLAKLALAL
>FLAK44 AM
FAKKLAKLAKKALAL
>FLAK50
FAKLLAKLAKKLL
>FLAK26V AM
VAKKLAKLAKKLAKLAL
>CAME-15
KWKLFKKIGAVLKVL
>FLAK50C
FAKLLAKLAKKAL
>FLAK50D
FAKLLAKALKKLL
>FLAK80
FAKLLAKKLL
>FLAK81
FAKKLAKALL
>FLAK82
FAKKLAKKLL
>FLAK83M
FAKLAKKLL
>FLAK 26 Ac
FAKKLAKLAKKLAKLAL
>Indolicidin
ILPWKWPWWPWRR
>FLAK-120G
VALALKALKKL
>FLAK-120F
WALAL
>D2A21
FAKKFAKKFKKFAKKFAKFAFAF
>KSL-1
KKVVFKVKFK
>FLAK50 Q7
FAKLLAKALKKFAL
>FLAK90
FAKLA
>FLAK91
FAKLF
>FLAK50 Q6
FAKLLAKALKKFL
>FLAK50 Q7
FAKLLAKALKKFAL
>FLAK50 T1
FAKLLAKLAK

**REMOVE REDUNDANT SEQUENCE USING CD-HIT**

In [ ]:
! cd-hit -i /content/Breast_fasta.fasta -o /content/Breast_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/Breast_fasta.fasta -o
         /content/Breast_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:31 2022
================================================================
                            Output
----------------------------------------------------------------
total seq: 95
longest and shortest : 38 and 12
Total letters: 1698
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90517486

comparing sequences from          0  to         95

       95  finished         74  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [ ]:
! grep ">" /content/Breast_fasta.fasta | wc -l

100

In [ ]:
! grep ">" /content/Breast_train_main_cdhit.txt | wc -l

74

In [ ]:
! cd-hit -i /content/Cervix_fasta.fasta -o /content/Cervix_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/Cervix_fasta.fasta -o
         /content/Cervix_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:32 2022
================================================================
                            Output
----------------------------------------------------------------
total seq: 95
longest and shortest : 38 and 11
Total letters: 1704
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90517483

comparing sequences from          0  to         95

       95  finished         72  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [ ]:
! grep ">" /content/Cervix_fasta.fasta | wc -l

100

In [ ]:
! grep ">" /content/Cervix_train_main_cdhit.txt | wc -l

72

In [ ]:
! cd-hit -i /content/Colon_fasta.fasta -o /content/Colon_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/Colon_fasta.fasta -o
         /content/Colon_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:32 2022
================================================================
                            Output
----------------------------------------------------------------
total seq: 94
longest and shortest : 38 and 12
Total letters: 1693
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90517506

comparing sequences from          0  to         94

       94  finished         72  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.10

In [ ]:
! grep ">" /content/Colon_fasta.fasta | wc -l

100

In [ ]:
! grep ">" /content/Colon_train_main_cdhit.txt | wc -l

72

In [ ]:
! cd-hit -i /content/Lungs_fasta.fasta -o /content/Lungs_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/Lungs_fasta.fasta -o
         /content/Lungs_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:33 2022
================================================================
                            Output
----------------------------------------------------------------
total seq: 96
longest and shortest : 38 and 12
Total letters: 1838
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90517448

comparing sequences from          0  to         96

       96  finished         67  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [ ]:
! grep ">" /content/Lungs_fasta.fasta | wc -l

100

In [ ]:
! grep ">" /content/Lungs_train_main_cdhit.txt | wc -l

67

In [ ]:
! cd-hit -i /content/Prostate_fasta.fasta -o /content/Prostate_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/Prostate_fasta.fasta -o
         /content/Prostate_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:33 2022
================================================================
                            Output
----------------------------------------------------------------
total seq: 87
longest and shortest : 38 and 11
Total letters: 1561
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90517660

comparing sequences from          0  to         87

       87  finished         63  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [ ]:
! grep ">" /content/Prostate_fasta.fasta | wc -l

100

In [ ]:
! grep ">" /content/Prostate_train_main_cdhit.txt | wc -l

63

In [ ]:
! cd-hit -i /content/skin_fasta.fasta -o /content/skin_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/skin_fasta.fasta -o
         /content/skin_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:34 2022
================================================================
                            Output
----------------------------------------------------------------
total seq: 85
longest and shortest : 38 and 11
Total letters: 1463
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90517727

comparing sequences from          0  to         85

       85  finished         55  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [ ]:
! grep ">" /content/skin_fasta.fasta | wc -l

100

In [ ]:
! grep ">" /content/skin_train_main_cdhit.txt | wc -l

55

In [ ]:
file = open("/content/skin_train_main_cdhit.txt", "r")
file.read()

'>Z10\nAAKKWAKAKWAKAKKWAKAA\n>Z9\nAAWKWAWAKKWAKAKKWAKAA\n>Z8\nAWKKWAKAWKWAKAKWWAKAA\n>FLAK50 Z9\nFAFAKIIAKIAKKII\n>FLAK50 Z7\nFAFGKGIGKIGKKGL\n>FLAK50 Z2\nFAFGKGIGKVGKKLL\n>FLAK50 Z3\nFAKAIAKIAFGKGIGKVGKKLL\n>FLAK50B\nFAKALAKLAKKLL\n>FLAK 17 C\nFAKALKALLKALKAL\n>FLAK50 Q1\nFAKFLAKFLKKAL\n>FLAK50 Z6\nFAKGVGKVGKKAL\n>FLAK50 Z8\nFAKIIAKIAKIAKKIL\n>FLAK77\nFAKKALKALKKL\n>D2A21\nFAKKFAKKFKKFAKKFAKFAFAF\n>FLAK 72\nFAKKLAKKAKLAKKL\n>FLAK 58\nFAKKLAKKLAKAAL\n>FLAK57\nFAKKLAKKLAKLAL\n>FLAK 56\nFAKKLAKKLAKLL\n>SHIVA DERIV P69 + KWKL\nFAKKLAKKLKKLAKKLAKKWKL\n>Anubis-2\nFAKKLAKKLKKLAKKLAKLAKKL\n>Buforin IIb\nRAGLQFPVGRLLRRLLRRLLR\n>Aurein1.2\nGLFDIIKKIAESF\n>Aurein2.5\nGLFDIVKKVVGAFGSL\n>Aurein2.6\nGLFDIAKKVIGVIGSL\n>Aurein 3.1\nGLFDIVKKIAGHIAGSI\n>Aurein 3.2\nGLFDIVKKIAGHIASSI\n>Aurein 3.3\nGLFDIVKKIAGHIVSSI\n>l3,10,13K7,8K4R2L9\nKLlRLLkkLlRLlLK\n>l3,4,8,10K5L7\nKlllKLKlKlLK\n>L6A/L17A\nKWKSFAKTFKSAKKTVAHTALKAISS\n>L17A\nKWKSFLKTFKSAKKTVAHTALKAISS\n>L21A\nKWKSFLKTFKSAKKTVAHTAAKAISS\n>P\nKWKSFLKTFKSAKKTVLHTALKAISS\n>L1\nPEWFKCRRWQWRMKKLGA\n>L2\nPAWFKARRWAWRMKKLAA\n>L3\nPAWRKAFRWAWRMKKLAA\n>L4\nPAWFKARRWAWRMLKKAA\n>L9\nPAWRKAARWAWRMLKKAA\n>Gaegurin peptides SEQID NO: 1\nFLGWLFKWAKK\n>Hecate AC\nFALALKALKKALKKLKKALKKAL\n>SB-37 AC\nMPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>SHIVA 10 AC\nFAKKLAKKLKKLAKKLAKLALAL\n>FLAK04 AM\nFALALKALKKLAKKLKKLAKKAL\n>FLAK06 AM\nFAKKLAKKLKKLAKLALAL\n>FLAK 25 AM\nFAKKLAKLAKKLAKLALAL\n>FLAK44 AM\nFAKKLAKLAKKALAL\n>FLAK50\nFAKLLAKLAKKLL\n>FLAK26V AM\nVAKKLAKLAKKLAKLAL\n>CAME-15\nKWKLFKKIGAVLKVL\n>FLAK50C\nFAKLLAKLAKKAL\n>FLAK50D\nFAKLLAKALKKLL\n>Indolicidin\nILPWKWPWWPWRR\n>FLAK-120G\nVALALKALKKL\n>FLAK50 Q7\nFAKLLAKALKKFAL\n>FLAK50 Q6\nFAKLLAKALKKFL\n'

In [ ]:
! cd-hit -i /content/negative_fasta.fasta -o /content/neg_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/negative_fasta.fasta -o
         /content/neg_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:34 2022
================================================================
                            Output
----------------------------------------------------------------
total seq: 233
longest and shortest : 50 and 11
Total letters: 6565
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 0M
Buffer          : 1 X 10M = 10M
Table           : 1 X 65M = 65M
Miscellaneous   : 0M
Total           : 75M

Table limit with the given memory limit:
Max number of representatives: 4000000
Max number of word counting entries: 90513865

comparing sequences from          0  to        233

      233  finished        231  clusters

Approximated maximum memory consumption: 75M
writing new database
writing clustering information
program completed !

Total CPU time 0.07

In [ ]:
! grep ">"  /content/negative_fasta.fasta | wc -l

250

In [ ]:
! grep ">"  /content/neg_train_main_cdhit.txt | wc -l

231

In [ ]:
file = open("/content/neg_train_main_cdhit.txt", "r")
file.read()

'>1\nLKKLLKWLLKLLK\n>2\nSFLTSFKDMAIKVAKDAGVNILNTISCKIFKTC\n>3\nNSGGAAVVAALGCAAGGVKYGRLLGPWGAAIG\n>5\nSFLSTFKELAINAAKNAGQSLLHTLSCKLDKTC\n>6\nDPVTCLKNGAICHPVFCPRRYKQIGTCGLPGTKCCK\n>7\nSNDSLWYGVGQFMGKQANCITNHPVKHMIIPGYCLSKILG\n>8\nLFGFLIPLLPHIIGAIPQVIGAIR\n>9\nWLGSALKIGAKLLPSVVGLFKKKKQ\n>10\nRWKVFKKIEKMGRNIRDGIVKAGPAIEVLGSAKALGK\n>11\nTLYRRFLCKKMKGRCETACLSFEKKIGTCRADLTPLCCKEKKKH\n>12\nKWKSFKKKLTSKFLHSAKKF\n>13\nASGWVCTLTIECGTVICAC\n>14\nNIWKKIASIAKEVLKAL\n>16\nALWKTMLKKLGTVALHAGKAALGAAADTISQGA\n>17\nRRAAVVLIVIRR\n>18\nDLFQVIKEKLKELTGGVIEGIQGV\n>19\nRWKVFKKIEKVGRNIRDGVIKAAPAIEVLGQAKAL\n>20\nCIKNGNGCQPNGSQGNCCSGYCHKQPGWVAGYCRRK\n>21\nKKSYPEYGSLDLRKECKMRRGHCKLQCSEKELRISFCIRPGTHCCM\n>22\nGLLSGILGAGKHIVCGLSGLR\n>23\nFTLKKSLLVLFFLGTISLSLCQEERAADEEDNGEVEE\n>24\nGLLDTIKNMALNAAKSAGVSVLNTLSCKLSKTC\n>25\nAALRGALRAVARVGKAILPHVAIANPYVRTPYVHNNP\n>26\nIASKFICTPGCAKTGSFNSYCC\n>27\nLLKLLKWLLKLLK\n>28\nITSISLCTPGCKTGALMGCNMKTATCNCSIHVSK\n>29\nAALRGCWTKSIPPKPCSGKR\n>30\nSLGVTLGAAGVYTATQTIATQIWKCGAVLTTSAECSRTGKSC\n>31\nIGPDTKKCVQRKNACHYFECPWLYYSVGTCYKGKGKCCQKRY\n>32\nFLPMLAGLAANFLPKIVCKITKKC\n>33\nINWSSIFEKVKNLV\n>34\nGIFSKISGKAIKNLFIKGAENVGKHVGIDVVRTGIDVVGCKIKGEC\n>35\nGLFGKILGVGKKVLCGLSGMC\n>36\nKVHGSLARAGK\n>37\nGIMDTVKNAAKDLAGQLLDKLKCKITAC\n>38\nGVLSNVIGYLKKLGTGALNAVLKQ\n>39\nINWLKLGKMVIDAL\n>40\nGINSLSSEMHKKCYKNGICRLECYESEMLVAYCMFQLECCVKGNPAP\n>41\nINMKASAAVAKKLL\n>43\nGLFLDTLKGAAKDVAGKLLEGLKCKIAGCKP\n>44\nRFIYMKGFGKPRFGKR\n>45\nSIFAFQDESPSAIAQAKLFK\n>46\nGIPCGESCVFIPCITGIAGCSCKSKVCYRN\n>47\nKTCENLANTYRGPCFTTGSCDDHCKNKEHLRSGRCRDDFRCWCTRNC\n>48\nGLFSILKGVGKIALKGLAKNMGKMGLDLVSCKISKEC\n>49\nSSMKLSFRARAYGFRGPGPQL\n>50\nRSNKGFNFMVDMIQALSK\n>51\nRLCRIVVIRVCR\n>52\nKPYCSCKWRCGIGEEEKGICHKFPIVTYVCCRRP\n>53\nKWKLFKKGIGAVLKV\n>54\nTTPLCVGVIIGLTTSIKICK\n>55\nSTIVCVSLRICNWSLRFCPSFKVRCPM\n>56\nRVCMAIPLPLCH\n>57\nITSFSLCTPGCAKTGSFNSYCC\n>58\nACQFWSCNSSCISRGYRQGYCWGIQYKYCQCQ\n>59\nFDIMGLIKKVAGAL\n>60\nFTMKKSPLLLFFLGTISLSLC\n>61\nLLGDFFRKAKEKIGKEFKRIVQR\n>62\nGVLDILKGAAKDLAGH\n>64\nGTQRCWNLYGKCRHRCSKKERVYVYCVNNKMCCVKPKYQPKERWWRF\n>65\nGILDTLKNLAKTAGKGALQGLVKMASCKLSGQC\n>66\nAILTTLANWARKFL\n>67\nMAADIISTIGDLVKLIINTVKKFQK\n>68\nVGECVRGRCPSGMCCSQFGYCGKGPKYCGR\n>69\nRLARRVVIRVAR\n>70\nVARGWKRKCPLFGKGG\n>71\nFFPIVGKRLYGLL\n>72\nVIDDLKKVAKKVRRELLCKKHHKKLN\n>73\nINWLKLGKKLLSAL\n>74\nINWLKLGKAIIDAL\n>75\nQSINNPITCLTKGGVCWGPCTGGFRQIGTCGLPRVRCCKKK\n>76\nKWKSFIKKLTSKFLHLAKKF\n>77\nSLWENFKNAGKQFILNILDKIRCRVAGGCRT\n>78\nLRDLKCFCRRKSCNWGEGIMGICKKRYGSPILCCR\n>79\nSVLGKSVAKHLPHVVPVIAEKT\n>80\nDDDQVEVQQEVKRGFLSTVKNLATNVAGTVIDTLKCKVTGGCRT\n>81\nQESKKGILLKPKTCNTNADCAKFCKGPIQNCLYHTCACVPGNPHCC\n>82\nQRPYTQPLIYYPPPPTPPRIYRA\n>83\nQEAQSVACTSYYCSKFCGSAGCSLYGCYLLHPGKICYCLHCSR\n>84\nSLGSFLKGVGTTLASVGKVVSDQFGKLLQAGQ\n>85\nSMWSGMWRRKLKKLRNALKKKLKGE\n>86\nFIKELLPHLSGIIDSVANAIK\n>87\nGLLGSLFGAGKKVACALSGLC\n>88\nRPRCWIKIKFRCKSLKF\n>89\nVAGPFRIPPLRREFQ\n>90\nGFWGKLWEGVKNAI\n>91\nGLRSKIWLWVLLMIWQESNKFKKM\n>92\nGILDSLKNLAKNAAQILLNKASCKLSGQC\n>93\nIIGPVLGLVGKPLESLLE\n>94\nQCVGTITLDQSDDLFDLNCNELQSVR\n>95\nDTTFCRCRVSCNILEKYSGKCELSGRTARICC\n>96\nATAWDFGPHGLLPIRPIRIRPLCGKDKS\n>97\nALLDKLKSLGKVVGKVAIGVAQHYLNPQ\n>99\nVTCFCRRRGCASRERHIGYCRFGNTIYRLCCRR\n>100\nWKPFKKIEKAVRRVRDGVAKAGPAVAVVGQAT\n>101\nATCDLASKWNWNHTLCAAHCIARRYRGGYCNSKAVCVCR\n>102\nGLLGAMFKVASKVLPHVVPAITEHF\n>103\nGILDFAKTVVGGIRNALGI\n>105\nVLPIIGNLLNSLL\n>106\nQLKSTCRIAEAWKGAKECNAKCAALGTTRGGVCQKFLGDLYCCCWD\n>107\nMFFSSKKCKTVSKTFRGPCVRNA\n>108\nRQRDPQQQYEQCQERCQRHETEPRHMQTCQQRCERRYEKEKRKQQKR\n>109\nVQLRIRVRVIRK\n>110\nGIGGALLSAGKAALKGLAKGFAEHF\n>111\nATCDALSFSSKWLTVNHSACAIHCLTKGYKGGRCVNTICNCRN\n>112\nDQYRCLQNGGFCLRSSCPSHTKLQGTCKPDKPNCCRS\n>113\nGSKKPVPIIYCNRRTGKCQR\n>114\nAVVNGVNYVGETTAA\n>115\nFLANQECFSEYRHCRMKCKANEYAIRYCADWTICCRVKKREAKKKIMW\n>116\nRRICRCRIGRCLGLEVYFGVCFLHGRLARRCCR\n>117\nANFEIVNNCPYTVWAAASPGGGRRLDRGQT\n>118\nSPIHACRYQRGVCIPGPCRWPYYRVGSCGSGLKSCCVRNRWA\n>119\nGVFTLIKGATQLIGKTLGKELGKTGLELMACKITEQC\n>120\nILPILGNLLNSLL\n>121\nFLSTALKVAANVVPTLFCKITKKC\n>122\nGVLDTFKDVAIGVAKGAGTGVLKALLCKLDKSC\n>123\nMGALIKTGAKIIGSGAAGGLGTYIGHKILGK\n>124\nGNRPVYIPPPRPPHPRL\n>125\nIDWLKLGKMVIDAL\n>126\nGLGKAQCAALWLQCASGGTIGCGGGAVACQNYRQFCR\n>127\nGIFTFEDESTTTVAPAKLYK\n>128\nQTCASRCPRPCNAGLCCSIYGYCGSGAAYCGAGNCRCQCRG\n>130\nPRCPPCPRCSWCPRCPTCPRCNCNPK\n>132\nFIGAILPAIAGLVGGLINR\n>133\nGVFLDALKKFAKGGMNAVLNPK\n>134\nSYVGDCGSNGGSCVSSYCPYGNRLNYFCPLGRTCCRRSY\n>135\nIIGVSEMERCHKKGGYCYFYCFSSHKKIGSCFPEWPRCCKNIK\n>136\nRKCLRWQWAMRKYGG\n>137\nGLPVCGETCFGGTCNTPGCTCSYPICTRN\n>138\nGIIDIAKKLVGGIRNVLGI\n>139\nGPGKWLPWLQPAYDFVTGLAKGIGKEGNKNKWKNV\n>140\nFLPAVIRVAANVLPTVFCAISKKC\n>141\nASVVKTTIKASKKLCKGATLTCGCNITGKK\n>142\nIRNSLTCRFNFGICLPKRCPGRMRQIGTCF\n>143\nGFGCPNNYQCHRHCKSIPGRCGGYCGGWHRLRCTCYRC\n>144\nILPIIGKILSTIF\n>145\nATCDLFSFRSKWVTPNHAGCAAHCIFLGNRGGRCVGTVCHCRK\n>146\nFLPLIGKVLSGIL\n>147\nGLFSKFAGKGIVNFLIEGVE\n>148\nGLLSGILNTAGGLLGNLIGSLSNGES\n>149\nFTCAISCDIKVNGKPCKGSGEKKCSGGWSCKFNVCVKV\n>150\nKEKLKLKCKAPKCYNDKLACT\n>151\nTTHSGKYYGNGVYCTKNKCTVDWAKATTCIAGMSIGGFLGGAIPGKC\n>152\nKINWGNVGGSCVGGAVIGGALGGLGGAGGGCITGAIGSIWDQW\n>155\nGLWQKIKDKASELVSGIVEGVK\n>156\nSIGSAFKKALPVAKKIGKAALPIAKAALP\n>157\nKYYGNGVSCNKKGCSVDWGKAIGIIGNNSAANLATGGAAGWSK\n>158\nGKIPVKAIKQAGKVIGKGLRAINIAGTTHDVVSFFRPKKKKH\n>159\nGLMDMVKGAAKNLFASALDTLKCKITGC\n>161\nGTTVVNSTFSIVLGNKGYICTVTVECMRNCSK\n>163\nHGPDSCNHDRGLCRVGNCNPGEYLAKYCFEPVILCCKPLSPTPTKT\n>164\nTPCGESCVYIPCISGVIGCSCTDKVCYLN\n>166\nFLPLLAGLAANFLPKLFCKITRKC\n>167\nGLWSKIKETGKEAAKAAGKAALNKIAEAV\n>170\nLFCKGGSCHFGGCPSHLIKVGSCFGFRSCCKWPWNA\n>171\nMPCSCKKYCDPWEVIDGSCGLFNSKYICCREK\n>172\nALWKDILKNAGKAALNEINQIVQ\n>173\nGFSSLFKAGAKYLLKSVGKAGAQQLACKAANNCA\n>174\nKKINNPVSCLRKGGRCWNRCIGNTRQIGSCGVPFLKCCKRK\n>175\nGLWNTKLEAGLLFAMGKLDLKRCLKAGGC\n>176\nLSCKRGTCHFGRCPSHLIKGSCSGG\n>177\nSIPCGESCVFIPCTVTALLGCSCKSKVCYKN\n>178\nRVCSAIPLPICH\n>179\nMTAQGNKPSSHDVITGRWTPSAADRAAGRVSGFGVITNIINGGLDC\n>180\nYENPYGCPTDEGKCFDRCNDSEFEGGYCGGSYRATCVCYRT\n>181\nFKTWKRPPFQTSCWGIIKE\n>182\nSGISGPLSCGRNGGVCIPIRCPVPMRQIGTCFGRPVKCCRSW\n>183\nSDYSRKRDPPQKYEEE\n>184\nGIFSTVFKAGKGIVCGLTGLC\n>185\nENDHRMPYELNRPNNLSKGGAKCGAAIA\n>186\nGDPTFCGETCRVIPVCTYSAALGCTCDDRSDGLCKRN\n>187\nGLMDTVKNAAKNLAGQLLDTIKCKMTGC\n>188\nNEEEKVKWEPDVP\n>189\nKRIVQRIKDFLRNLVPRTES\n>190\nDKLIGSCVWGAVNYTSDCNGECLLRGYKGGHCGSFANVNCWCET\n>191\nGLLDTFKNLALNAAKSAGVSVLNSLSCKLSKTC\n>192\nRDCRSQSKTFVGLCVSDTNCASVCLTEHFPGGKCDGYRRCFCTKDC\n>194\nGLWKSLLKNVGKAAGKAALNAVTDMVNQS\n>195\nRIIDLLWRVRRPQKPKFVTVWVR\n>196\nGLWNSIKIAGKKLFVNVLDKIRCKVAGGCKTSPDVE\n>197\nFLPIVAGLAANFLPKIVCKITKKC\n>198\nFLPIIAGIAAKVFPKIFCAISKKC\n>199\nSLQYVMSAGPYTWYKDTRTGKTICKQTIDTASYTFGVMAEGWGKTFH\n>200\nINWKKIKSIIKAAMN\n>201\nSDCNINSNTAADVILCFNQVGSCALCSPTLVGGPVP\n>202\nAPVPFSCTRGCLTHLV\n>203\nRQRDPQQQYEQCQKHCQRRETEPRHMQTCQQRCERRYEKEKRKQQKR\n>205\nDIGGSRQGCVA\n>206\nQRFSQPTFKLPQGRLTLSRKF\n>207\nSVSCLRNKGVCMPGKCAPKMKQIGTCGMPQVKCCKRK\n>208\nILPFVAGVAAMEMEHVYCAASKKC\n>209\nQETCHDLIMKRDCDEATCVNMCQQKWKGSGGSCFQNFNVMSCICNFPCQV\n>210\nILGPVLGLVSNALGGLIKKI\n>211\nHEPCGESCVFIPCITTVVGCSCKNKVCYN\n>212\nGLKDKFKSMGEKLKQYIQTWKAKF\n>213\nSRWPSPGRPRPFPGRPKPIFRPRPCNCYAPPCPCDRW\n>214\nRVCRRRSAGFKGVCMSDHNCAQVCLQEGYGGGNCDGIMRQCKCIRQC\n>215\nAISCGQVSSAIGPCLSYARGQGSAPSAGCC\n>217\nGFKDWIKGAAKKLIKTVAANIANQ\n>218\nNWYVKKCLNDVGICKKKCKPEELHVKNGRAMCGKQRDCCVPAD\n>219\nVFGTLGSTDDSLFGRYKQDIFNDHRGHLQGQAYGSR\n>220\nFKCRRWQWRAKKLGA\n>221\nSIYERCELARELINR\n>222\nGKREKCLRRNGFCAFLKCPTLSVISGTCSRFQVCC\n>223\nVLSIVACSSGCGSGKTAASCVETCGNRCFTNVGSLC\n>224\nRKFHEKHHSHRGYRSNYLYDN\n>225\nGGTIFDCGESCFLGTCYTKGCSCGEWKLCYGTN\n>226\nGFLDTLKNMALNAAKGAGGSVLKALFCKLFKTC\n>227\nMDVVRTLILCVCLFGLTFA\n>228\nGFWKKVGSAAWGGVKAAAKGAAVGGLNALAKHIQ\n>229\nGICRCLCRRGVCRCICVL\n>230\nGRFRRLRKKTRKRLKKIGKV\n>231\nKWKLFKKLKVLTTGL\n>232\nAVDLAKIANIANKVLSSLFGK\n>233\nEALYNSEDLYEETSDSDD\n>234\nALFSILRGLKKLGKMGQAFVNCEIYKKC\n>235\nSWLSKTYKKLENSAKKRISEGVAIAILGGLR\n>236\nGIGASILSAGKSALKGFAKGLAEHFAN\n>237\nGIGAAILSAGKSALKGLAKGLAEHF\n>238\nQSISCAESCVWIPCATSLIGCSCVNSRCIYSK\n>239\nKRKCPKTPFDNTPGAWFAHLILGC\n>240\nLGWGRRCPQCPRCPSCPSCPRCPRCPRCKCNPK\n>241\nGLLDTFKNLAINAAESAGVSVLNSLSCKLSKTC\n>242\nLRDLVCYCRKRGCKRRERMNGTCRKGHLMYTLCCR\n>243\nGTQRCWNLYGKCRYRCSKKERVYVYCINNKMCCVKPKYQPKERWWPF\n>244\nTNYGNGVGVPDAIMAGIIKLIFIFNIRQGYNFGKKAT\n>245\nGLLDVVKGAAKNLLASALDKLKCKVTGC\n>246\nFLPMLAGLAANFLPKLFCKITKKC\n>247\nSASVLKTSIKVSKKYCKGVTLTCGCNITGGK\n>248\nGLWQKIKNAAGDLASGIVEGIKS\n>249\nGIFSLVKGAAKLAGKGLAKEGGKFGLELIACKIAKQC\n'

In [ ]:
! cd-hit -i /content/Positive_fasta.fasta -o /content/Positive_train_main_cdhit.txt -c 0.99

================================================================
Program: CD-HIT, V4.8.1, Mar 01 2019, 14:14:47
Command: cd-hit -i /content/Positive_fasta.fasta -o
         /content/Positive_train_main_cdhit.txt -c 0.99

Started: Fri Jul 15 06:03:34 2022
================================================================
                            Output
----------------------------------------------------------------

Fatal Error:
Failed to open the database file
Program halted !!

In [ ]:
! cat /content/Breast_train_main_cdhit.txt /content/Cervix_train_main_cdhit.txt /content/Colon_train_main_cdhit.txt /content/Lungs_train_main_cdhit.txt /content/Prostate_train_main_cdhit.txt /content/skin_train_main_cdhit.txt > /content/Combined_Pos_cdhit.txt

In [ ]:
file = open("/content/Combined_Pos_cdhit.txt", "r")
file.read()

'>L6A/L17A\nKWKSFAKTFKSAKKTVAHTALKAISS\n>L17A/L21A\nKWKSFLKTFKSAKKTVAHTAAKAISS\n>L17A\nKWKSFLKTFKSAKKTVAHTALKAISS\n>L6A\nKWKSFAKTFKSAKKTVLHTALKAISS\n>P\nKWKSFLKTFKSAKKTVLHTALKAISS\n>A12L\nKWKSFLKTFKSLKKTVLHTALKAISS\n>A20L\nKWKSFLKTFKSAKKTVLHTLLKAISS\n>A12L/A20L\nKWKSFLKTFKSLKKTVLHTLLKAISS\n>A12L/A20L/A23L\nKWKSFLKTFKSLKKTVLHTLLKLISS\n>RGD-La\nRGDLLRHVVKILEKYL\n>RGD-Las\nRGDLLRHVVKILSKYL\n>Hecate Ac\nFALALKALKKALKKLKKALKKAL\n>SB-37 AC\nMPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>FLAK01 AM\nFALAAKALKKLAKKLKKLAKKAL\n>FLAK03 AM\nFALALKALKKLLKKLKKLAKKAL\n>FLAK04 AM\nFALALKALKKLAKKLKKLAKKAL\n>FLAK05 AM\nFALAKLAKKAKAKLKKALKAL\n>FLAK06 AM\nFALALKALKKLKKALKKAL\n>FLAK06 R-AC\nFAKKLAKKLKKLAKLALAL\n>KAL V\nVALALKALKKALKKLKKALKKAL\n>FLAK 17 AM\nFALALKKALKALKKAL\n>FLAK 25 AM\nFAKKLAKLAKKLAKLALAL\n>FLAK43 AM\nFAKKLAKLAKKLLAL\n>FLAK44 AM\nFAKKLAKLAKKALAL\n>FLAK62 AM\nFALAKKALKKAKKAL\n>FLAK 06R-AM\nFAKKLAKKLKKLAKLALAK\n>MSI-78 AM\nGIGKFLKKAKKFGKAFVKILKK\n>FLAK50\nFAKLLAKLAKKLL\n>FLAK51\nFAKKLAKLALKLAKL\n>FLAK57\nFAKKLAKKLAKLAL\n>FLAK71\nFAKKLKKLAKLAKKL\n>FLAK77\nFAKKALKALKKL\n>FLAK50V\nVAKLLAKLAKKLL\n>FLAK26V AM\nVAKKLAKLAKKLAKLAL\n>CAME-15\nKWKLFKKIGAVLKVL\n>FLAK50D\nFAKLLAKALKKLL\n>FLAK 50E\nFAKLLKLAAKKLL\n>Indolicidin\nILPWKWPWWPWRR\n>FLAK 17 C\nFAKALKALLKALKAL\n>FLAK 50H\nFAKLLAKLAKAKL\n>FLAK 50G\nFAKLLAKLAKLKL\n>SHIVA DERIV P69 + KWKL\nFAKKLAKKLKKLAKKLAKKWKL\n>CA (1-7) Shiva10 (1-16)\nKWKLFKKKTKLFKKFAKKLAKKL\n>FLAK 56\nFAKKLAKKLAKLL\n>FLAK 58\nFAKKLAKKLAKAAL\n>FLAK 72\nFAKKLAKKAKLAKKL\n>FLAK 75\nFAKKLKKLAKKL\n>SHIVA 10 (1-16) Ac\nKTKLFKKFAKKLAKKLKKLAKKL\n>FLAK50B\nFAKALAKLAKKLL\n>FLAK50I\nFAKLLALALKLKL\n>FLAK50K\nFAKLLAKLAKAKA\n>FLAK50L\nFAKLLAKLAKAKG\n>Shiva-11\nFAKKLAKKLKKLAKKLAKLALALKALALKAL\n>SHIVA 11[(1-16)ME(2-9]-COOH\nFAKKLAKKLKKLAKKLIGAVLKV\n>FLAK 50N\nFAKLLAKALKLKL\n>CA(1-& HECATE(11/23)\nKWKLFKKALKKLKKALKKAL\n>PYL-ME\nKIAKVALAKLGIGAVLKVLTTGL\n>VISHNU3\nMPKEKVFLKIEKMGRNIRN\n>MELITTIIN\nGIGAVLKVLTTGLPALISWIKRKRQQ\n>FLAG26-D3\nFAKKLLAKALKL\n>FLAK50 Q1\nFAKFLAKFLKKAL\n>FLAK50 Q2\nFAKLLFKALKKAL\n>FLAK50 Q3\nFAKLLAKFLKKAL\n>FLAK50 Q4\nFAKLLAKAFKKAL\n>FLAK50 Q5\nFAKLFAKAFKKAL\n>FLAK50 Q6\nFAKLLAKALKKFL\n>FLAK50 Q7\nFAKLLAKALKKFAL\n>FLAK50 Q8\nFAKLLAKLAKKFAL\n>FLAK50 Q9\nFAKLFAKLAKKFAL\n>FLAK50 Q10\nFKLAFKLAKKAFL\n>FLAK50 T2\nFAKLLAKLAKKVL\n>FLAK50 T3\nFAKLLAKLAKKIL\n>FLAK50 T4\nFAKLLAKLAKKEL\n>FLAK50 T5\nFAKLLAKLAKKSL\n>Cationic Amphiphilic\nGIIKKIIIKKIIIKKI\n>L6A/L17A\nKWKSFAKTFKSAKKTVAHTALKAISS\n>L17A/L21A\nKWKSFLKTFKSAKKTVAHTAAKAISS\n>L17A\nKWKSFLKTFKSAKKTVAHTALKAISS\n>L6A\nKWKSFAKTFKSAKKTVLHTALKAISS\n>P\nKWKSFLKTFKSAKKTVLHTALKAISS\n>A12L\nKWKSFLKTFKSLKKTVLHTALKAISS\n>A20L\nKWKSFLKTFKSAKKTVLHTLLKAISS\n>A12L/A20L\nKWKSFLKTFKSLKKTVLHTLLKAISS\n>A12L/A20L/A23L\nKWKSFLKTFKSLKKTVLHTLLKLISS\n>RGD-La\nRGDLLRHVVKILEKYL\n>RGD-Las\nRGDLLRHVVKILSKYL\n>Hecate AC\nFALALKALKKALKKLKKALKKAL\n>SB-37 AC\nMPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>FLAK01 AM\nFALAAKALKKLAKKLKKLAKKAL\n>FLAK03 AM\nFALALKALKKLLKKLKKLAKKAL\n>FLAK04 AM\nFALALKALKKLAKKLKKLAKKAL\n>FLAK05 AM\nFALAKLAKKAKAKLKKALKAL\n>FLAK06 AM\nFALALKALKKLKKALKKAL\n>FLAK06 R-AC\nFAKKLAKKLKKLAKLALAL\n>KAL V\nVALALKALKKALKKLKKALKKAL\n>FLAK 17 AM\nFALALKKALKALKKAL\n>FLAK 25 AM\nFAKKLAKLAKKLAKLALAL\n>FLAK43 AM\nFAKKLAKLAKKLLAL\n>FLAK44 AM\nFAKKLAKLAKKALAL\n>FLAK62 AM\nFALAKKALKKAKKAL\n>FLAK 06R-AM\nFAKKLAKKLKKLAKLALAK\n>MSI-78 AM\nGIGKFLKKAKKFGKAFVKILKK\n>FLAK50\nFAKLLAKLAKKLL\n>FLAK51\nFAKKLAKLALKLAKL\n>FLAK57\nFAKKLAKKLAKLAL\n>FLAK71\nFAKKLKKLAKLAKKL\n>FLAK77\nFAKKALKALKKL\n>FLAK50V\nVAKLLAKLAKKLL\n>FLAK26V AM\nVAKKLAKLAKKLAKLAL\n>CAME-15\nKWKLFKKIGAVLKVL\n>FLAK50D\nFAKLLAKALKKLL\n>FLAK 50E\nFAKLLKLAAKKLL\n>Indolicidin\nILPWKWPWWPWRR\n>FLAK 50H\nFAKLLAKLAKAKL\n>FLAK 50G\nFAKLLAKLAKLKL\n>SHIVA DERIV P69 + KWKL\nFAKKLAKKLKKLAKKLAKKWKL\n>CA(1-7) Shiva10(1-16)\nKWKLFKKKTKLFKKFAKKLAKKL\n>FLAK 56\nFAKKLAKKLAKLL\n>FLAK 58\nFAKKLAKKLAKAAL\n>FLAK 72\nFAKKLAKKAKLAKKL\n>FLAK 75\nFAKKLKKLAKKL\n>SHIVA 10 (1-16) Ac\nKTKLFKKFAKKLAKKLKKLAKKL\n>FLAK50B\nFAKALAKLAKKLL\n>FLAK50J\nFAKLLAKLAKKAA\n>FLAK50I\nFAKLLALALKLKL\n>FLAK50K\nFAKLLAKLAKAKA\n>FLAK50L\nFAKLLAKLAKAKG\n>Shiva-11\nFAKKLAKKLKKLAKKLAKLALALKALALKAL\n>SHIVA 11[(1-16)ME(2-9]-COOH\nFAKKLAKKLKKLAKKLIGAVLKV\n>FLAK 50N\nFAKLLAKALKLKL\n>CA(1-& HECATE(11/23)\nKWKLFKKALKKLKKALKKAL\n>PYL-ME\nKIAKVALAKLGIGAVLKVLTTGL\n>VISHNU3\nMPKEKVFLKIEKMGRNIRN\n>MELITTIIN\nGIGAVLKVLTTGLPALISWIKRKRQQ\n>FLAG26-D3\nFAKKLLAKALKL\n>FLAK50 Q1\nFAKFLAKFLKKAL\n>FLAK50 Q2\nFAKLLFKALKKAL\n>FLAK50 Q3\nFAKLLAKFLKKAL\n>FLAK50 Q5\nFAKLFAKAFKKAL\n>FLAK50 Q6\nFAKLLAKALKKFL\n>FLAK50 Q7\nFAKLLAKALKKFAL\n>FLAK50 Q8\nFAKLLAKLAKKFAL\n>FLAK50 Q9\nFAKLFAKLAKKFAL\n>FLAK50 Q10\nFKLAFKLAKKAFL\n>FLAK50 T2\nAKLLAKLAKKVL\n>Epinecidin-8\nFIFHIIKGLFHAGKMI\n>L6A/L17A\nKWKSFAKTFKSAKKTVAHTALKAISS\n>L17A/L21A\nKWKSFLKTFKSAKKTVAHTAAKAISS\n>L17A\nKWKSFLKTFKSAKKTVAHTALKAISS\n>L6A\nKWKSFAKTFKSAKKTVLHTALKAISS\n>P\nKWKSFLKTFKSAKKTVLHTALKAISS\n>A12L\nKWKSFLKTFKSLKKTVLHTALKAISS\n>A20L\nKWKSFLKTFKSAKKTVLHTLLKAISS\n>A12L/A20L\nKWKSFLKTFKSLKKTVLHTLLKAISS\n>A12L/A20L/A23L\t\nKWKSFLKTFKSLKKTVLHTLLKLISS\n>Tat-a5\nKAQIRAMECNILGRKKRRQRRR\n>RGD-La\nRGDLLRHVVKILEKYL\n>RGD-Las\nRGDLLRHVVKILSKYL\n>Hecate AC\nFALALKALKKALKKLKKALKKAL\n>SB-37 AC\nMPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>FLAK01 AM\nFALAAKALKKLAKKLKKLAKKAL\n>FLAK03 AM\nFALALKALKKLLKKLKKLAKKAL\n>FLAK04 AM\nFALALKALKKLAKKLKKLAKKAL\n>FLAK05 AM\nFALAKLAKKAKAKLKKALKAL\n>FLAK06 AM\nFALALKALKKLKKALKKAL\n>FLAK06 R-AC\t\nFAKKLAKKLKKLAKLALAL\n>KAL V\nVALALKALKKALKKLKKALKKAL\n>FLAK 17 AM\nFALALKKALKALKKAL\n>FLAK 25 AM\nFAKKLAKLAKKLAKLALAL\n>FLAK43 AM\nFAKKLAKLAKKLLAL\n>FLAK44 AM\nFAKKLAKLAKKALAL\n>FLAK62 AM\nFALAKKALKKAKKAL\n>FLAK 06R-AM\nFAKKLAKKLKKLAKLALAK\n>MSI-78 AM\nGIGKFLKKAKKFGKAFVKILKK\n>FLAK50\nFAKLLAKLAKKLL\n>FLAK51\nFAKKLAKLALKLAKL\n>FLAK57\nFAKKLAKKLAKLAL\n>FLAK71\nFAKKLKKLAKLAKKL\n>FLAK77\nFAKKALKALKKL\n>FLAK50V\nVAKLLAKLAKKLL\n>FLAK26V AM\nVAKKLAKLAKKLAKLAL\n>CAME-15\nKWKLFKKIGAVLKVL\n>FLAK50D\nFAKLLAKALKKLL\n>FLAK 50E\nFAKLLKLAAKKLL\n>Indolicidin\nILPWKWPWWPWRR\n>FLAK 17 C\nFAKALKALLKALKAL\n>FLAK 50H\nFAKLLAKLAKAKL\n>FLAK 50G\nFAKLLAKLAKLKL\n>SHIVA DERIV P69 + KWKL\nFAKKLAKKLKKLAKKLAKKWKL\n>CA(1-7) Shiva10(1-16)\nKWKLFKKKTKLFKKFAKKLAKKL\n>FLAK 56\nFAKKLAKKLAKLL\n>FLAK 58\nFAKKLAKKLAKAAL\n>FLAK 72\nFAKKLAKKAKLAKKL\n>FLAK 75\nFAKKLKKLAKKL\n>SHIVA 10 (1-16) Ac\nKTKLFKKFAKKLAKKLKKLAKKL\n>FLAK50B\nFAKALAKLAKKLL\n>FLAK50I\nFAKLLALALKLKL\n>FLAK50K\nFAKLLAKLAKAKA\n>FLAK50L\nFAKLLAKLAKAKG\n>Shiva-11\nFAKKLAKKLKKLAKKLAKLALALKALALKAL\n>SHIVA 11[(1-16)ME(2-9]-COOH\nFAKKLAKKLKKLAKKLIGAVLKV\n>FLAK 50N\nFAKLLAKALKLKL\n>CA(1-& HECATE(11/23)\nKWKLFKKALKKLKKALKKAL\n>PYL-ME\nKIAKVALAKLGIGAVLKVLTTGL\n>VISHNU3\nMPKEKVFLKIEKMGRNIRN\n>MELITTIIN\nGIGAVLKVLTTGLPALISWIKRKRQQ\n>FLAG26-D3\nFAKKLLAKALKL\n>FLAK50 Q1\nFAKFLAKFLKKAL\n>FLAK50 Q2\nFAKLLFKALKKAL\n>FLAK50 Q3\nFAKLLAKFLKKAL\n>FLAK50 Q4\nFAKLLAKAFKKAL\n>FLAK50 Q5\nFAKLFAKAFKKAL\n>FLAK50 Q6\nFAKLLAKALKKFL\n>FLAK50 Q7\nFAKLLAKALKKFAL\n>FLAK50 Q8\nFAKLLAKLAKKFAL\n>FLAK50 Q9\nFAKLFAKLAKKFAL\n>FLAK50 Q10\nFKLAFKLAKKAFL\n>FLAK50 T2\nFAKLLAKLAKKVL\n>L6A/L17A\nKWKSFAKTFKSAKKTVAHTALKAISS\n>L17A/L21A\nKWKSFLKTFKSAKKTVAHTAAKAISS\n>L17A\nKWKSFLKTFKSAKKTVAHTALKAISS\n>L6A\nKWKSFAKTFKSAKKTVLHTALKAISS\t\n>P\nKWKSFLKTFKSAKKTVLHTALKAISS\n>A12L\nKWKSFLKTFKSLKKTVLHTALKAISS\n>A20L\nKWKSFLKTFKSAKKTVLHTLLKAISS\n>A12L/A20L\nKWKSFLKTFKSLKKTVLHTLLKAISS\n>A12L/A20L/A23L\t\nKWKSFLKTFKSLKKTVLHTLLKLISS\n>RGD-La\nRGDLLRHVVKILEKYL\n>RGD-Las\nRGDLLRHVVKILSKYL\n>Hecate AC\nFALALKALKKALKKLKKALKKAL\n>SB-37 AC\nMPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>FLAK01 AM\nFALAAKALKKLAKKLKKLAKKAL\n>FLAK03 AM\nFALALKALKKLLKKLKKLAKKAL\n>FLAK04 AM\nFALALKALKKLAKKLKKLAKKAL\n>FLAK05 AM\nFALAKLAKKAKAKLKKALKAL\n>FLAK06 AM\t\nFALALKALKKLKKALKKAL\n>FLAK06 AM\nFAKKLAKKLKKLAKLALAL\n>KAL V\nVALALKALKKALKKLKKALKKAL\n>FLAK 17 AMV\nFALALKKALKALKKAL\n>FLAK 25 AM\nFAKKLAKLAKKLAKLALAL\n>FLAK43 AM\nFAKKLAKLAKKLLAL\n>FLAK44 AM\nFAKKLAKLAKKALAL\n>FLAK62 AM\nFALAKKALKKAKKAL\n>FLAK 06R-AM\nFAKKLAKKLKKLAKLALAK\n>MSI-78 AM\nGIGKFLKKAKKFGKAFVKILKK\n>FLAK50\nFAKLLAKLAKKLL\n>FLAK51\nFAKKLAKLALKLAKL\n>FLAK57\nFAKKLAKKLAKLAL\n>FLAK71\nFAKKLKKLAKLAKKL\n>FLAK77\nFAKKALKALKKL\n>FLAK50V\nVAKLLAKLAKKLL\n>FLAK26V AM\nVAKKLAKLAKKLAKLAL\n>CAME-15\nKWKLFKKIGAVLKVL\n>FLAK50C\nFAKLLAKLAKKAL\n>FLAK50D\nFAKLLAKALKKLL\n>FLAK 50E\nFAKLLKLAAKKLL\n>Indolicidin\nILPWKWPWWPWRR\n>FLAK 17 C\nFAKALKALLKALKAL\n>FLAK 50H\nFAKLLAKLAKAKL\n>FLAK 50G\nFAKLLAKLAKLKL\n>SHIVA DERIV P69 + KWKL\nFAKKLAKKLKKLAKKLAKKWKL\n>CA(1-7)Shiva10(1-16)\t\nKWKLFKKKTKLFKKFAKKLAKKL\n>FLAK 56\nFAKKLAKKLAKLL\n>FLAK 58\nFAKKLAKKLAKAAL\n>FLAK 72\nFAKKLAKKAKLAKKL\n>FLAK 75\nFAKKLKKLAKKL\n>SHIVA 10 (1-16)\t\nKTKLFKKFAKKLAKKLKKLAKKL\n>FLAK50B\nFAKALAKLAKKLL\n>FLAK50J\nFAKLLAKLAKKAA\n>FLAK50I\nFAKLLALALKLKL\n>FLAK50K\nFAKLLAKLAKAKA\n>FLAK50L\nFAKLLAKLAKAKG\n>Shiva-11\nFAKKLAKKLKKLAKKLAKLALALKALALKAL\n>SHIVA 11[(1-16)ME(2-9]-COOH\nFAKKLAKKLKKLAKKLIGAVLKV\n>FLAK 50N\nFAKLLAKALKLKL\n>FLAK 50O\nFAKLLAKALKKAL\n>CA(1-& HECATE(11/23)\nKWKLFKKALKKLKKALKKAL\n>PYL-ME\nKIAKVALAKLGIGAVLKVLTTGL\n>VISHNU3\nMPKEKVFLKIEKMGRNIRN\n>MELITTIIN\nGIGAVLKVLTTGLPALISWIKRKRQQ\n>FLAG26-D3\t\nFAKKLLAKALKL\n>FLAK50 Q1\nFAKFLAKFLKKAL\n>FLAK50 Q2\t\nFAKLLFKALKKAL\n>FLAK50 Q3\t\nFAKLLAKFLKKAL\n>FLAK50 Q4\nFAKLLAKAFKKAL\n>EB(H2R)-lytic\nYRWYGYTPQNVIGGGKLlLKlLkkLLKlLKKK\n>EB-Lytic\nYHWYGYTPQNVIGGGKLlLKlLkkLLKlLKKK\n>FLAK50T9\nYAKLLAKLAKKAL\n>KAL V\nVALALKALKKALKKLKKALKKAL\n>FLAK50T8\nVAKLLAKLAKKVL\n>FLAK50V\nVAKLLAKLAKKLL\n>FLAK26V AM\nVAKKLAKLAKKLAKLAL\n>Transferrin receptor (TfR)-lytic hybrid peptide\nTHRPPMWSPVWPGGGKLlLKlLkkLLKlLKKK\n>Buforin IIb\nRAGLQFPVGRLLRRLLRRLLR\n>SB-37 AC\nMPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>VISHNU3\nMPKEKVFLKIEKMGRNIRN\n>DL6R6\nlRRllRRllRRl\n>LSB-37\nLPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>LL 37\nLLGDFFRKSKEKIGKEFKRIVQRIKDFLRNLVPRTES\n>D-K6L9\nLKlLKKLlkKLLkLL\n>DL6K6\nlKKllKKllKKl\n>Flak 96L\nLKKLAKLALAF\n>FLAK98\nKYKKALKKLAKLL\n>CA(1-7)Shiva10(1-16)\nKWKLFKKKTKLFKKFAKKLAKKL\n>CAME-15\nKWKLFKKIGAVLKVL\n>CA(1-& HECATE(11/23)\nKWKLFKKALKKLKKALKKAL\n>FLAK93B\nKWKLAKKALALL\n>SHIVA 10 (1-16) Ac\nKTKLFKKFAKKLAKKLKKLAKKL\n>FLAK100-CO2H\nKLLKLLLKLYKKLLKLL\n>FLAK99\nKLALKLALKALKAAKLA\n>Modelin-5\nKLAKKLAKLAKLAKAL\n>PYL-ME\nKIAKVALAKLGIGAVLKVLTTGL\n>FLAK92B\nKAKLAKKALAKLL\n>Indolicidin\nILPWKWPWWPWRR\n>Adenoregulin\nGLWSKIKEVGKEAAKAAAKAAGKAALGAVSEAV\n>22\nGLFKVIKKVASVIGGL\n>23\nGLFKVIKKVAKVIKKL\n>ltc2aG11A\nGLFGKLIKKFARKAISYAVKKARGKH\n>13\nGLFDVIKKVASVIKKL\n>11\nGLFDVIKKVASVIKGL\n>Citropin 1.1\nGLFDVIKKVASVIGGL\n>7\nGLFDVIKKVAAVIGGL\n>Aurein2.5\nGLFDIVKKVVGAFGSL\n>Aurein 3.3\nGLFDIVKKIAGHIVSSI\n>Aurein 3.2\nGLFDIVKKIAGHIASSI\n>Aurein 3.1\nGLFDIVKKIAGHIAGSI\n>Aurein1.2\nGLFDIIKKIAESF\n>Aurein2.6\nGLFDIAKKVIGVIGSL\n>MSI-78 AM\nGIGKFLKKAKKFGKAFVKILKK\n>Magainin 2\nGIGKFLHSAKKFGKAFVGEIMNS\n>Magainin G\nGIGKFLHSAKKFAKAFVAEIMNS\n>Magainin B\nGIGKFLHAAKKFAKAFVAEIMNS\n>MELITTIIN\nGIGAVLKVLTTGLPALISWIKRKRQQ\n>Gaegurin peptides SEQID NO: 4\nFLWWLFKWAWK\n>TsAP-S1\nFLSLIPKLVKKIIKAFK\n>Gaegurin peptides SEQID NO: 2\nFLKWLFKWAKK\n>PTP5\nFLKLLKKLAAKLF\n>PTP4\nFLKLLKKLAAKFLPTIICKISYKC\n>PTP8\nFLKLLAGLLKNFA\n>Gaegurin peptides SEQID NO: 3\nFLGWLFKWAWK\n>FLAK50\nFAKLLAKLAKKLL\n>FLAK50 T3\nFAKLLAKLAKKIL\n>FLAK50T7\nFAKLLAKLAKKGL\n>FLAK50 Q8\nFAKLLAKLAKKFAL\n>FLAK50 T4\nFAKLLAKLAKKEL\n>FLAK50J\nFAKLLAKLAKKAA\n>FLAK50L\nFAKLLAKLAKAKG\n>FLAK50K\nFAKLLAKLAKAKA\n>Z10\nAAKKWAKAKWAKAKKWAKAA\n>Z9\nAAWKWAWAKKWAKAKKWAKAA\n>Z8\nAWKKWAKAWKWAKAKWWAKAA\n>FLAK50 Z9\nFAFAKIIAKIAKKII\n>FLAK50 Z7\nFAFGKGIGKIGKKGL\n>FLAK50 Z2\nFAFGKGIGKVGKKLL\n>FLAK50 Z3\nFAKAIAKIAFGKGIGKVGKKLL\n>FLAK50B\nFAKALAKLAKKLL\n>FLAK 17 C\nFAKALKALLKALKAL\n>FLAK50 Q1\nFAKFLAKFLKKAL\n>FLAK50 Z6\nFAKGVGKVGKKAL\n>FLAK50 Z8\nFAKIIAKIAKIAKKIL\n>FLAK77\nFAKKALKALKKL\n>D2A21\nFAKKFAKKFKKFAKKFAKFAFAF\n>FLAK 72\nFAKKLAKKAKLAKKL\n>FLAK 58\nFAKKLAKKLAKAAL\n>FLAK57\nFAKKLAKKLAKLAL\n>FLAK 56\nFAKKLAKKLAKLL\n>SHIVA DERIV P69 + KWKL\nFAKKLAKKLKKLAKKLAKKWKL\n>Anubis-2\nFAKKLAKKLKKLAKKLAKLAKKL\n>Buforin IIb\nRAGLQFPVGRLLRRLLRRLLR\n>Aurein1.2\nGLFDIIKKIAESF\n>Aurein2.5\nGLFDIVKKVVGAFGSL\n>Aurein2.6\nGLFDIAKKVIGVIGSL\n>Aurein 3.1\nGLFDIVKKIAGHIAGSI\n>Aurein 3.2\nGLFDIVKKIAGHIASSI\n>Aurein 3.3\nGLFDIVKKIAGHIVSSI\n>l3,10,13K7,8K4R2L9\nKLlRLLkkLlRLlLK\n>l3,4,8,10K5L7\nKlllKLKlKlLK\n>L6A/L17A\nKWKSFAKTFKSAKKTVAHTALKAISS\n>L17A\nKWKSFLKTFKSAKKTVAHTALKAISS\n>L21A\nKWKSFLKTFKSAKKTVAHTAAKAISS\n>P\nKWKSFLKTFKSAKKTVLHTALKAISS\n>L1\nPEWFKCRRWQWRMKKLGA\n>L2\nPAWFKARRWAWRMKKLAA\n>L3\nPAWRKAFRWAWRMKKLAA\n>L4\nPAWFKARRWAWRMLKKAA\n>L9\nPAWRKAARWAWRMLKKAA\n>Gaegurin peptides SEQID NO: 1\nFLGWLFKWAKK\n>Hecate AC\nFALALKALKKALKKLKKALKKAL\n>SB-37 AC\nMPKWKVFKKIEKVGRNIRNGIVKAGPAIAVLGEAKALG\n>SHIVA 10 AC\nFAKKLAKKLKKLAKKLAKLALAL\n>FLAK04 AM\nFALALKALKKLAKKLKKLAKKAL\n>FLAK06 AM\nFAKKLAKKLKKLAKLALAL\n>FLAK 25 AM\nFAKKLAKLAKKLAKLALAL\n>FLAK44 AM\nFAKKLAKLAKKALAL\n>FLAK50\nFAKLLAKLAKKLL\n>FLAK26V AM\nVAKKLAKLAKKLAKLAL\n>CAME-15\nKWKLFKKIGAVLKVL\n>FLAK50C\nFAKLLAKLAKKAL\n>FLAK50D\nFAKLLAKALKKLL\n>Indolicidin\nILPWKWPWWPWRR\n>FLAK-120G\nVALALKALKKL\n>FLAK50 Q7\nFAKLLAKALKKFAL\n>FLAK50 Q6\nFAKLLAKALKKFL\n'

In [ ]:
 ! grep ">" /content/Combined_Pos_cdhit.txt | wc -l

403

In [ ]:
! cat /content/Combined_Pos_cdhit.txt /content/neg_train_main_cdhit.txt > /content/data.txt

In [ ]:
! grep ">"  /content/data.txt | wc -l

634

**CALCULATING FEATURE USING PFEATURE LIBRARY**

In [ ]:
import pandas as pd

Amino Acid Composition

In [ ]:
# Amino acid composition (AAC)

from Pfeature.pfeature import aac_wp

def aac(input):
  a = input.rstrip('txt')
  output = a + 'aac.csv'
  df_out = aac_wp(input, output)
  df_in = pd.read_csv(output)
  return df_in

aac('/content/Breast_train_main_cdhit.txt')

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,AAC_M,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y
0,19.23,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
1,19.23,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
2,15.38,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
3,15.38,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
4,11.54,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,11.54,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,23.08,0.0,0.0,0.00,23.08,0.0,0.00,0.00,30.77,23.08,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
70,23.08,0.0,0.0,0.00,7.69,0.0,0.00,0.00,30.77,30.77,0.0,0.0,0.0,0.0,0.0,0.00,0.00,7.69,0.00,0.0
71,23.08,0.0,0.0,0.00,7.69,0.0,0.00,7.69,30.77,30.77,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
72,23.08,0.0,0.0,7.69,7.69,0.0,0.00,0.00,30.77,30.77,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
73,23.08,0.0,0.0,0.00,7.69,0.0,0.00,0.00,30.77,30.77,0.0,0.0,0.0,0.0,0.0,7.69,0.00,0.00,0.00,0.0

In [ ]:
! ls -l

In [ ]:
#Calculate feature for each cancer data + combining the data + merge with cancer type

Bre = '/content/Breast_train_main_cdhit.txt'
Cer = '/content/Cervix_train_main_cdhit.txt'
Col = '/content/Colon_train_main_cdhit.txt'
Lun = '/content/Lungs_train_main_cdhit.txt'
Pro = '/content/Prostate_train_main_cdhit.txt'
Ski = '/content/skin_train_main_cdhit.txt'
neg = '/content/neg_train_main_cdhit.txt'

def feature_calc(Bre, Cer, Col, Lun, Pro, Ski, neg, feature_name):
  # Calculate cancer feature
  Bre_feature = feature_name(Bre)
  Cer_feature = feature_name(Cer)
  Col_feature = feature_name(Col)
  Lun_feature = feature_name(Lun)
  Pro_feature = feature_name(Pro)
  Ski_feature = feature_name(Ski)
  neg_feature = feature_name(neg)
  
  Bre_Cer_Col_Lun_Pro_Ski_neg_feature = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature, neg_feature], axis=0)
 
  # Combine feature
  df = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature, neg_feature], join="inner")
  return df

feature = feature_calc(Bre, Cer, Col, Lun, Pro, Ski, neg, aac) # AAC
feature

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,AAC_M,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y
0,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,0.00,0.00,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00
1,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,0.00,0.00,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00
2,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,0.00,0.00,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00
3,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,0.00,0.00,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00
4,11.54,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,11.54,0.00,0.00,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,14.29,7.14,7.14,0.00,0.00,10.71,0.00,0.00,17.86,21.43,0.00,3.57,0.00,0.00,0.0,3.57,3.57,10.71,0.00,0.00
227,12.50,8.33,0.00,0.00,12.50,4.17,0.00,4.17,16.67,20.83,4.17,4.17,8.33,0.00,0.0,0.00,4.17,0.00,0.00,0.00
228,3.23,9.68,0.00,0.00,0.00,12.90,0.00,6.45,19.35,6.45,0.00,3.23,0.00,0.00,0.0,12.90,12.90,9.68,0.00,3.23
229,13.04,0.00,4.35,4.35,0.00,17.39,0.00,13.04,13.04,8.70,0.00,4.35,0.00,4.35,0.0,8.70,0.00,4.35,4.35,0.00
230,16.22,5.41,0.00,5.41,5.41,18.92,0.00,8.11,18.92,13.51,0.00,0.00,0.00,2.70,0.0,2.70,0.00,2.70,0.00,0.00

In [ ]:
import pandas as pd

Br = pd.read_csv("/content/Breast_train_main_cdhit.aac.csv")
Ce = pd.read_csv("/content/Cervix_train_main_cdhit.aac.csv")
Co = pd.read_csv("/content/Colon_train_main_cdhit.aac.csv")
Lu = pd.read_csv("/content/Lungs_train_main_cdhit.aac.csv")
Pr = pd.read_csv("/content/Prostate_train_main_cdhit.aac.csv")
Sk = pd.read_csv("/content/skin_train_main_cdhit.aac.csv")
Ne = pd.read_csv("/content/neg_train_main_cdhit.aac.csv")
#df = pd.concat(([Br, Ce, Co, Lu, Pr, Sk], axis=0))
#df

In [ ]:
aac_data = pd.concat([Br, Ce, Co, Lu, Pr, Sk, Ne], join = "inner")
aac_data

#save
aac_data.to_csv(r"/content/aac_data.csv", index=False)

In [ ]:
Br.head()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,AAC_M,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0

In [ ]:
Co.head()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,AAC_M,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0

In [ ]:
Br.shape

(74, 20)

In [ ]:
Ce.shape

(72, 20)

In [ ]:
inner_merged = pd.merge(Br, Ce)
inner_merged

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,AAC_M,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
2,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
3,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
4,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
109,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
110,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
111,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0
112,28.57,0.0,0.0,0.0,21.43,0.0,0.00,0.00,28.57,21.43,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0

In [ ]:
inner_merged.shape

(113, 20)

In [ ]:
Br['Tissue'] = 'Breast' 
Co['Tissue'] = 'Colon'
Ce['Tissue'] = 'Cervix'
Lu['Tissue'] = 'Lungs'
Sk['Tissue'] = 'Skin'
Pr['Tissue'] = 'Prostate'

In [ ]:
concatenated = pd.concat([Br, Ce, Co, Lu, Pr, Sk], join="inner")
concatenated

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y,Tissue
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,23.08,0.0,0.0,0.0,7.69,0.0,0.00,0.00,30.77,38.46,...,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,Skin
51,0.00,0.0,0.0,0.0,0.00,0.0,0.00,7.69,7.69,7.69,...,0.0,23.08,0.0,15.38,0.00,0.00,0.00,38.46,0.0,Skin
52,27.27,0.0,0.0,0.0,0.00,0.0,0.00,0.00,27.27,36.36,...,0.0,0.00,0.0,0.00,0.00,0.00,9.09,0.00,0.0,Skin
53,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,...,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,Skin
54,23.08,0.0,0.0,0.0,15.38,0.0,0.00,0.00,30.77,30.77,...,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,Skin

In [ ]:
concatenated['Class'] = 'Positive'
concatenated

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y,Tissue,Class
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast,Positive
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast,Positive
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast,Positive
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast,Positive
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,Breast,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,23.08,0.0,0.0,0.0,7.69,0.0,0.00,0.00,30.77,38.46,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,Skin,Positive
51,0.00,0.0,0.0,0.0,0.00,0.0,0.00,7.69,7.69,7.69,...,23.08,0.0,15.38,0.00,0.00,0.00,38.46,0.0,Skin,Positive
52,27.27,0.0,0.0,0.0,0.00,0.0,0.00,0.00,27.27,36.36,...,0.00,0.0,0.00,0.00,0.00,9.09,0.00,0.0,Skin,Positive
53,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,Skin,Positive
54,23.08,0.0,0.0,0.0,15.38,0.0,0.00,0.00,30.77,30.77,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,Skin,Positive

In [ ]:
Ne = pd.read_csv("/content/neg_train_main_cdhit.aac.csv")
Ne.head()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,AAC_M,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,38.46,53.85,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,7.69,0.00
1,9.09,6.06,6.06,0.00,9.09,3.03,0.00,12.12,15.15,6.06,3.03,6.06,0.00,0.00,0.00,9.09,9.09,6.06,0.00,0.00
2,25.00,3.12,0.00,0.00,0.00,28.12,0.00,3.12,3.12,9.38,0.00,3.12,3.12,0.00,3.12,3.12,0.00,9.38,3.12,3.12
3,12.12,6.06,3.03,3.03,6.06,3.03,3.03,3.03,12.12,18.18,0.00,6.06,0.00,3.03,0.00,12.12,9.09,0.00,0.00,0.00
4,2.78,16.67,2.78,0.00,2.78,11.11,2.78,5.56,11.11,5.56,0.00,2.78,11.11,2.78,5.56,0.00,8.33,5.56,0.00,2.78

In [ ]:
Ne['Class'] = 'Negative'
Ne['Tissue'] = 'Negative'

In [ ]:
ACP_Dataset_aac = pd.concat([concatenated, Ne], axis=0, join="inner")
ACP_Dataset_aac

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y,Tissue,Class
0,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,...,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00,Breast,Positive
1,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,...,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00,Breast,Positive
2,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,...,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00,Breast,Positive
3,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,...,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00,Breast,Positive
4,11.54,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,11.54,...,0.00,0.00,0.0,15.38,11.54,3.85,3.85,0.00,Breast,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,14.29,7.14,7.14,0.00,0.00,10.71,0.00,0.00,17.86,21.43,...,0.00,0.00,0.0,3.57,3.57,10.71,0.00,0.00,Negative,Negative
227,12.50,8.33,0.00,0.00,12.50,4.17,0.00,4.17,16.67,20.83,...,8.33,0.00,0.0,0.00,4.17,0.00,0.00,0.00,Negative,Negative
228,3.23,9.68,0.00,0.00,0.00,12.90,0.00,6.45,19.35,6.45,...,0.00,0.00,0.0,12.90,12.90,9.68,0.00,3.23,Negative,Negative
229,13.04,0.00,4.35,4.35,0.00,17.39,0.00,13.04,13.04,8.70,...,0.00,4.35,0.0,8.70,0.00,4.35,4.35,0.00,Negative,Negative
230,16.22,5.41,0.00,5.41,5.41,18.92,0.00,8.11,18.92,13.51,...,0.00,2.70,0.0,2.70,0.00,2.70,0.00,0.00,Negative,Negative

In [ ]:
ACP_Dataset_aac.tail()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y,Tissue,Class
226,14.29,7.14,7.14,0.00,0.00,10.71,0.0,0.00,17.86,21.43,...,0.00,0.00,0.0,3.57,3.57,10.71,0.00,0.00,Negative,Negative
227,12.50,8.33,0.00,0.00,12.50,4.17,0.0,4.17,16.67,20.83,...,8.33,0.00,0.0,0.00,4.17,0.00,0.00,0.00,Negative,Negative
228,3.23,9.68,0.00,0.00,0.00,12.90,0.0,6.45,19.35,6.45,...,0.00,0.00,0.0,12.90,12.90,9.68,0.00,3.23,Negative,Negative
229,13.04,0.00,4.35,4.35,0.00,17.39,0.0,13.04,13.04,8.70,...,0.00,4.35,0.0,8.70,0.00,4.35,4.35,0.00,Negative,Negative
230,16.22,5.41,0.00,5.41,5.41,18.92,0.0,8.11,18.92,13.51,...,0.00,2.70,0.0,2.70,0.00,2.70,0.00,0.00,Negative,Negative

In [ ]:
ACP_Dataset_aac.shape

(634, 22)

In [ ]:
ACP_Dataset_aac.to_csv(r"/content/ACP_Dataset_aac.csv", index=False)

Dipeptide Amino Acid (DPC)

In [ ]:
from Pfeature.pfeature import dpc_wp

def dpc(input):
  a = input.rstrip('txt')
  output = a + 'dpc.csv'
  df_out = dpc_wp(input, output, 1)
  df_in = pd.read_csv(output)
  return df_in

dpc('/content/Combined_Pos_cdhit.txt')

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YM,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY
0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.67,8.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,30.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
401,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.38,15.38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
402,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.67,8.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from Pfeature.pfeature import dpc_wp

def dpc(input):
  a = input.rstrip('txt')
  output = a + 'dpc.csv'
  df_out = dpc_wp(input, output, 1)
  df_in = pd.read_csv(output)
  return df_in

dpc('/content/neg_train_main_cdhit.txt')

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YM,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY
0,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.00,0.00,0.0,0.0,0.0,3.12,0.0,3.12,3.12,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12.90,0.00,0.0,0.0,0.0,3.23,0.0,3.23,0.00,3.23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.12,0.00,0.0,0.0,0.0,3.12,0.0,3.12,3.12,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.00,0.0,0.0,0.0,0.00,0.0,2.86,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,3.70,0.00,0.0,0.0,0.0,0.00,0.0,0.00,3.70,3.70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
227,4.35,0.00,0.0,0.0,0.0,4.35,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
228,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
229,4.55,0.00,0.0,0.0,0.0,4.55,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
230,2.78,2.78,0.0,0.0,0.0,2.78,0.0,0.00,8.33,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
pos_dpc = pd.read_csv("/content/Combined_Pos_cdhit.dpc.csv")
#labelling data
pos_dpc['Class'] = 'Positive'
pos_dpc.head()

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY,Class
0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Positive
1,4.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Positive
2,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Positive
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Positive
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Positive

In [ ]:
neg_dpc = pd.read_csv("/content/neg_train_main_cdhit.dpc.csv")
neg_dpc['Tissue'] = 'Negative'
neg_dpc['Class'] = 'Negative'
neg_dpc.head()

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY,Tissue,Class
0,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Negative,Negative
1,0.00,0.0,0.0,0.0,0.0,3.12,0.0,3.12,3.12,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Negative,Negative
2,12.90,0.0,0.0,0.0,0.0,3.23,0.0,3.23,0.00,3.23,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Negative,Negative
3,3.12,0.0,0.0,0.0,0.0,3.12,0.0,3.12,3.12,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Negative,Negative
4,0.00,0.0,0.0,0.0,0.0,0.00,0.0,2.86,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Negative,Negative

In [ ]:
#feature extraction of DPC_Data

Bre = '/content/Breast_train_main_cdhit.txt'
Cer = '/content/Cervix_train_main_cdhit.txt'
Col = '/content/Colon_train_main_cdhit.txt'
Lun = '/content/Lungs_train_main_cdhit.txt'
Pro = '/content/Prostate_train_main_cdhit.txt'
Ski = '/content/skin_train_main_cdhit.txt'

def feature_calc(Bre, Cer, Col, Lun, Pro, Ski, feature_name):
  # Calculate cancer feature
  Bre_feature = feature_name(Bre)
  Cer_feature = feature_name(Cer)
  Col_feature = feature_name(Col)
  Lun_feature = feature_name(Lun)
  Pro_feature = feature_name(Pro)
  Ski_feature = feature_name(Ski)
 
  Bre_Cer_Col_Lun_Pro_Ski_neg_feature = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature], axis=0)
 
  # Combine feature and class
  df = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature], join="inner")
  return df

feature = feature_calc(Bre, Cer, Col, Lun, Pro, Ski, dpc) # DPC
feature

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YM,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY
0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.67,8.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,30.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.38,15.38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.67,8.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#reading the csv File

Br = pd.read_csv("/content/Breast_train_main_cdhit.dpc.csv")
Ce = pd.read_csv("/content/Cervix_train_main_cdhit.dpc.csv")
Co = pd.read_csv("/content/Colon_train_main_cdhit.dpc.csv")
Lu = pd.read_csv("/content/Lungs_train_main_cdhit.dpc.csv")
Pr = pd.read_csv("/content/Prostate_train_main_cdhit.dpc.csv")
Sk = pd.read_csv("/content/skin_train_main_cdhit.dpc.csv")
Ne = pd.read_csv("/content/neg_train_main_cdhit.dpc.csv")

In [ ]:
dpc_data = pd.concat([Br, Ce, Co, Lu, Pr, Sk, Ne], join = "inner")


#save
dpc_data.to_csv(r"/content/dpc_data.csv", index=False)

dpc_data

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YM,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY
0,0.00,0.00,0.0,0.0,0.0,0.00,4.0,4.0,8.00,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.00,0.00,0.0,0.0,0.0,0.00,4.0,4.0,8.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.00,0.00,0.0,0.0,0.0,0.00,4.0,4.0,4.00,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.00,0.0,0.0,0.0,0.00,0.0,4.0,8.00,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.00,0.0,0.0,0.0,0.00,0.0,4.0,4.00,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,3.70,0.00,0.0,0.0,0.0,0.00,0.0,0.0,3.70,3.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
227,4.35,0.00,0.0,0.0,0.0,4.35,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
228,0.00,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
229,4.55,0.00,0.0,0.0,0.0,4.55,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
230,2.78,2.78,0.0,0.0,0.0,2.78,0.0,0.0,8.33,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
Sk.head()

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YM,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY
0,10.53,0.0,0.0,0.0,0.00,0.0,0.0,0.0,31.58,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,20.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,20.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,0.0,0.0,0.0,7.14,0.0,0.0,0.0,21.43,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.00,0.0,0.0,0.0,7.14,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Labelling Data

Br['Tissue'] = 'Breast' 
Co['Tissue'] = 'Colon'
Ce['Tissue'] = 'Cervix'
Lu['Tissue'] = 'Lungs'
Sk['Tissue'] = 'Skin'
Pr['Tissue'] = 'Prostate'

In [ ]:
Br.head()

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY,Tissue
0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
1,4.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
2,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast

In [ ]:
concatenate = pd.concat([Br, Co, Ce, Lu, Pr, Sk], join="inner")
concatenate

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY,Tissue
0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
1,4.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
2,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.00,4.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.67,8.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Skin
51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Skin
52,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,30.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Skin
53,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.38,15.38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Skin
54,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.67,8.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Skin

In [ ]:
concatenate['Class'] = 'Positive'

In [ ]:
#Combine Data

ACP_Dataset_dpc=pd.concat([concatenate, neg_dpc], join="inner")
ACP_Dataset_dpc.head()

,DPC1_AA,DPC1_AC,DPC1_AD,DPC1_AE,DPC1_AF,DPC1_AG,DPC1_AH,DPC1_AI,DPC1_AK,DPC1_AL,...,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY,Tissue,Class
0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast,Positive
1,4.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,8.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast,Positive
2,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast,Positive
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast,Positive
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Breast,Positive

In [ ]:
ACP_Dataset_dpc.to_csv(r"/content/ACP_Dataset_dpc.csv", index=False)

In [ ]:
ACP_Dataset_dpc.Tissue

0        Breast
1        Breast
2        Breast
3        Breast
4        Breast
         ...
226    Negative
227    Negative
228    Negative
229    Negative
230    Negative
Name: Tissue, Length: 634, dtype: object

In [ ]:
Tissue = ACP_Dataset_dpc.Tissue
Class = ACP_Dataset_dpc.Class

Tissue.to_csv(r"/content/Tissue.csv", index=False)
Tissue

0        Breast
1        Breast
2        Breast
3        Breast
4        Breast
         ...
226    Negative
227    Negative
228    Negative
229    Negative
230    Negative
Name: Tissue, Length: 634, dtype: object

Physico-Chemical Properties (PCP)

In [ ]:
from Pfeature.pfeature import pcp_wp

def pcp(input):
  a = input.rstrip('txt')
  output = a + 'pcp.csv'
  df_out = pcp_wp(input, output)
  df_in = pd.read_csv(output)
  return df_in

pcp('/content/Combined_Pos_cdhit.txt')

,PCP_PC,PCP_NC,PCP_NE,PCP_PO,PCP_NP,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,...,PCP_SA_EX,PCP_SA_IN,PCP_TN,PCP_SM,PCP_LR,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5
0,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.346,0.500,0.500,0.306,-0.465,-0.575,0.223,0.327
1,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.346,0.500,0.500,0.306,-0.465,-0.575,0.223,0.327
2,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.308,0.462,0.538,0.132,-0.426,-0.656,0.201,0.309
3,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.308,0.462,0.538,0.132,-0.426,-0.656,0.201,0.309
4,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.269,0.423,0.577,-0.042,-0.387,-0.736,0.178,0.291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,0.308,0.0,0.692,0.000,0.692,0.615,0.000,0.077,0.0,0.308,...,0.308,0.000,0.231,0.231,0.769,-1.211,-0.612,-1.119,0.191,0.671
399,0.231,0.0,0.769,0.000,0.769,0.385,0.231,0.385,0.0,0.231,...,0.308,0.231,0.000,0.231,0.769,-1.971,1.798,-0.325,1.785,-0.068
400,0.273,0.0,0.727,0.000,0.727,0.727,0.000,0.000,0.0,0.273,...,0.273,0.000,0.273,0.364,0.636,-1.102,-1.103,-1.197,0.029,0.743
401,0.286,0.0,0.714,0.000,0.714,0.571,0.000,0.143,0.0,0.286,...,0.286,0.000,0.286,0.286,0.714,-1.103,-0.503,-0.814,0.257,0.611
402,0.308,0.0,0.692,0.000,0.692,0.538,0.000,0.154,0.0,0.308,...,0.308,0.000,0.231,0.231,0.769,-1.206,-0.363,-0.923,0.288,0.558

In [ ]:
from Pfeature.pfeature import pcp_wp

def pcp(input):
  a = input.rstrip('txt')
  output = a + 'pcp.csv'
  df_out = pcp_wp(input, output)
  df_in = pd.read_csv(output)
  return df_in

pcp('/content/neg_train_main_cdhit.txt')

,PCP_PC,PCP_NC,PCP_NE,PCP_PO,PCP_NP,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,...,PCP_SA_EX,PCP_SA_IN,PCP_TN,PCP_SM,PCP_LR,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5
0,0.385,0.000,0.615,0.000,0.615,0.538,0.000,0.077,0.000,0.385,...,0.385,0.000,0.000,0.000,1.000,-1.759,-0.055,-1.715,0.450,0.449
1,0.152,0.061,0.788,0.242,0.485,0.364,0.000,0.091,0.061,0.152,...,0.273,0.212,0.273,0.545,0.455,-0.165,-0.720,-0.185,-0.368,-0.039
2,0.062,0.000,0.938,0.094,0.812,0.781,0.031,0.062,0.000,0.062,...,0.094,0.094,0.594,0.750,0.250,-0.019,-1.867,0.000,-0.273,0.162
3,0.152,0.061,0.788,0.303,0.424,0.364,0.000,0.061,0.061,0.152,...,0.273,0.242,0.333,0.515,0.485,0.153,-0.688,-0.132,-0.434,0.131
4,0.194,0.028,0.778,0.306,0.444,0.417,0.111,0.056,0.028,0.194,...,0.306,0.250,0.306,0.611,0.389,0.229,-0.762,0.143,0.020,-0.235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,0.179,0.071,0.750,0.143,0.571,0.571,0.000,0.000,0.071,0.179,...,0.286,0.071,0.357,0.607,0.393,0.034,-1.280,-0.364,-0.393,0.195
227,0.167,0.000,0.833,0.125,0.667,0.500,0.083,0.125,0.000,0.167,...,0.292,0.167,0.250,0.417,0.583,-1.113,-0.560,-0.095,0.125,0.128
228,0.194,0.000,0.806,0.387,0.387,0.387,0.000,0.032,0.000,0.194,...,0.226,0.290,0.387,0.645,0.355,0.441,-1.327,-0.361,-0.391,-0.199
229,0.130,0.087,0.783,0.130,0.609,0.565,0.000,0.043,0.087,0.130,...,0.304,0.087,0.391,0.522,0.478,0.230,-1.124,-0.416,-0.494,0.220
230,0.189,0.054,0.757,0.108,0.649,0.595,0.000,0.054,0.054,0.189,...,0.270,0.027,0.432,0.459,0.541,-0.006,-1.350,-0.443,-0.284,0.177

In [ ]:
#feature extraction of PCP_Data

Bre = '/content/Breast_train_main_cdhit.txt'
Cer = '/content/Cervix_train_main_cdhit.txt'
Col = '/content/Colon_train_main_cdhit.txt'
Lun = '/content/Lungs_train_main_cdhit.txt'
Pro = '/content/Prostate_train_main_cdhit.txt'
Ski = '/content/skin_train_main_cdhit.txt'

def feature_calc(Bre, Cer, Col, Lun, Pro, Ski, feature_name):
  # Calculate cancer feature
  Bre_feature = feature_name(Bre)
  Cer_feature = feature_name(Cer)
  Col_feature = feature_name(Col)
  Lun_feature = feature_name(Lun)
  Pro_feature = feature_name(Pro)
  Ski_feature = feature_name(Ski)
 
  Bre_Cer_Col_Lun_Pro_Ski_neg_feature = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature], axis=0)
 
  # Combine feature and class
  df = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature], join="inner")
  return df

feature = feature_calc(Bre, Cer, Col, Lun, Pro, Ski, pcp) #PCP
feature

,PCP_PC,PCP_NC,PCP_NE,PCP_PO,PCP_NP,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,...,PCP_SA_EX,PCP_SA_IN,PCP_TN,PCP_SM,PCP_LR,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5
0,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.346,0.500,0.500,0.306,-0.465,-0.575,0.223,0.327
1,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.346,0.500,0.500,0.306,-0.465,-0.575,0.223,0.327
2,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.308,0.462,0.538,0.132,-0.426,-0.656,0.201,0.309
3,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.308,0.462,0.538,0.132,-0.426,-0.656,0.201,0.309
4,0.308,0.0,0.692,0.269,0.423,0.308,0.000,0.115,0.0,0.308,...,0.269,0.308,0.269,0.423,0.577,-0.042,-0.387,-0.736,0.178,0.291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,0.308,0.0,0.692,0.000,0.692,0.615,0.000,0.077,0.0,0.308,...,0.308,0.000,0.231,0.231,0.769,-1.211,-0.612,-1.119,0.191,0.671
51,0.231,0.0,0.769,0.000,0.769,0.385,0.231,0.385,0.0,0.231,...,0.308,0.231,0.000,0.231,0.769,-1.971,1.798,-0.325,1.785,-0.068
52,0.273,0.0,0.727,0.000,0.727,0.727,0.000,0.000,0.0,0.273,...,0.273,0.000,0.273,0.364,0.636,-1.102,-1.103,-1.197,0.029,0.743
53,0.286,0.0,0.714,0.000,0.714,0.571,0.000,0.143,0.0,0.286,...,0.286,0.000,0.286,0.286,0.714,-1.103,-0.503,-0.814,0.257,0.611
54,0.308,0.0,0.692,0.000,0.692,0.538,0.000,0.154,0.0,0.308,...,0.308,0.000,0.231,0.231,0.769,-1.206,-0.363,-0.923,0.288,0.558

In [ ]:
Br = pd.read_csv("/content/Breast_train_main_cdhit.pcp.csv")
Ce = pd.read_csv("/content/Cervix_train_main_cdhit.pcp.csv")
Co = pd.read_csv("/content/Colon_train_main_cdhit.pcp.csv")
Lu = pd.read_csv("/content/Lungs_train_main_cdhit.pcp.csv")
Pr = pd.read_csv("/content/Prostate_train_main_cdhit.pcp.csv")
Sk = pd.read_csv("/content/skin_train_main_cdhit.pcp.csv")
Ne = pd.read_csv("/content/neg_train_main_cdhit.pcp.csv")

In [ ]:
pcp_data = pd.concat([Br, Ce, Co, Lu, Pr, Sk, Ne], join = "inner")


#save
pcp_data.to_csv(r"/content/pcp_data.csv", index=False)

pcp_data

,PCP_PC,PCP_NC,PCP_NE,PCP_PO,PCP_NP,PCP_AL,PCP_CY,PCP_AR,PCP_AC,PCP_BS,...,PCP_SA_EX,PCP_SA_IN,PCP_TN,PCP_SM,PCP_LR,PCP_Z1,PCP_Z2,PCP_Z3,PCP_Z4,PCP_Z5
0,0.308,0.000,0.692,0.269,0.423,0.308,0.000,0.115,0.000,0.308,...,0.269,0.308,0.346,0.500,0.500,0.306,-0.465,-0.575,0.223,0.327
1,0.308,0.000,0.692,0.269,0.423,0.308,0.000,0.115,0.000,0.308,...,0.269,0.308,0.346,0.500,0.500,0.306,-0.465,-0.575,0.223,0.327
2,0.308,0.000,0.692,0.269,0.423,0.308,0.000,0.115,0.000,0.308,...,0.269,0.308,0.308,0.462,0.538,0.132,-0.426,-0.656,0.201,0.309
3,0.308,0.000,0.692,0.269,0.423,0.308,0.000,0.115,0.000,0.308,...,0.269,0.308,0.308,0.462,0.538,0.132,-0.426,-0.656,0.201,0.309
4,0.308,0.000,0.692,0.269,0.423,0.308,0.000,0.115,0.000,0.308,...,0.269,0.308,0.269,0.423,0.577,-0.042,-0.387,-0.736,0.178,0.291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,0.179,0.071,0.750,0.143,0.571,0.571,0.000,0.000,0.071,0.179,...,0.286,0.071,0.357,0.607,0.393,0.034,-1.280,-0.364,-0.393,0.195
227,0.167,0.000,0.833,0.125,0.667,0.500,0.083,0.125,0.000,0.167,...,0.292,0.167,0.250,0.417,0.583,-1.113,-0.560,-0.095,0.125,0.128
228,0.194,0.000,0.806,0.387,0.387,0.387,0.000,0.032,0.000,0.194,...,0.226,0.290,0.387,0.645,0.355,0.441,-1.327,-0.361,-0.391,-0.199
229,0.130,0.087,0.783,0.130,0.609,0.565,0.000,0.043,0.087,0.130,...,0.304,0.087,0.391,0.522,0.478,0.230,-1.124,-0.416,-0.494,0.220
230,0.189,0.054,0.757,0.108,0.649,0.595,0.000,0.054,0.054,0.189,...,0.270,0.027,0.432,0.459,0.541,-0.006,-1.350,-0.443,-0.284,0.177

Pseudo Amino-acid Composition (PAAC)

In [ ]:
from Pfeature.pfeature import paac_wp

def paac(input):
  a = input.rstrip('txt')
  output = a + 'paac.csv'
  df_out = paac_wp(input, output, 2, 0.05)
  df_in = pd.read_csv(output)
  return df_in

paac('/content/Combined_Pos_cdhit.txt')

,PAAC2_A,PAAC2_C,PAAC2_D,PAAC2_E,PAAC2_F,PAAC2_G,PAAC2_H,PAAC2_I,PAAC2_K,PAAC2_L,...,PAAC2_P,PAAC2_Q,PAAC2_R,PAAC2_S,PAAC2_T,PAAC2_V,PAAC2_W,PAAC2_Y,PAAC2_lam1,PAAC2_lam2
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0947,0.1023
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0903,0.1027
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0923,0.1041
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0928,0.1030
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,...,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0904,0.1048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,23.08,0.0,0.0,0.0,7.69,0.0,0.00,0.00,30.77,38.46,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0961,0.1352
399,0.00,0.0,0.0,0.0,0.00,0.0,0.00,7.69,7.69,7.69,...,23.08,0.0,15.38,0.00,0.00,0.00,38.46,0.0,0.1377,0.0984
400,27.27,0.0,0.0,0.0,0.00,0.0,0.00,0.00,27.27,36.36,...,0.00,0.0,0.00,0.00,0.00,9.09,0.00,0.0,0.0878,0.1019
401,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.1021,0.1270
402,23.08,0.0,0.0,0.0,15.38,0.0,0.00,0.00,30.77,30.77,...,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0999,0.1374

In [ ]:
from Pfeature.pfeature import paac_wp

def paac(input):
  a = input.rstrip('txt')
  output = a + 'paac_1.csv'
  df_out = paac_wp(input, output, 1, 0.05)
  df_in = pd.read_csv(output)
  return df_in

paac('/content/Combined_Pos_cdhit.txt')

,PAAC1_A,PAAC1_C,PAAC1_D,PAAC1_E,PAAC1_F,PAAC1_G,PAAC1_H,PAAC1_I,PAAC1_K,PAAC1_L,...,PAAC1_N,PAAC1_P,PAAC1_Q,PAAC1_R,PAAC1_S,PAAC1_T,PAAC1_V,PAAC1_W,PAAC1_Y,PAAC1_lam1
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.1055
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.1007
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.1030
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.1035
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,...,0.0,0.00,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.1010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,23.08,0.0,0.0,0.0,7.69,0.0,0.00,0.00,30.77,38.46,...,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.1112
399,0.00,0.0,0.0,0.0,0.00,0.0,0.00,7.69,7.69,7.69,...,0.0,23.08,0.0,15.38,0.00,0.00,0.00,38.46,0.0,0.1527
400,27.27,0.0,0.0,0.0,0.00,0.0,0.00,0.00,27.27,36.36,...,0.0,0.00,0.0,0.00,0.00,0.00,9.09,0.00,0.0,0.0977
401,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,...,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.1170
402,23.08,0.0,0.0,0.0,15.38,0.0,0.00,0.00,30.77,30.77,...,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.1158

In [ ]:
from Pfeature.pfeature import paac_wp

def paac(input):
  a = input.rstrip('txt')
  output = a + 'paac_1.csv'
  df_out = paac_wp(input, output, 1, 0.05)
  df_in = pd.read_csv(output)
  return df_in

paac('/content/neg_train_main_cdhit.txt')

,PAAC1_A,PAAC1_C,PAAC1_D,PAAC1_E,PAAC1_F,PAAC1_G,PAAC1_H,PAAC1_I,PAAC1_K,PAAC1_L,...,PAAC1_N,PAAC1_P,PAAC1_Q,PAAC1_R,PAAC1_S,PAAC1_T,PAAC1_V,PAAC1_W,PAAC1_Y,PAAC1_lam1
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,38.46,53.85,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,7.69,0.00,0.1324
1,9.09,6.06,6.06,0.00,9.09,3.03,0.00,12.12,15.15,6.06,...,6.06,0.00,0.00,0.00,9.09,9.09,6.06,0.00,0.00,0.0860
2,25.00,3.12,0.00,0.00,0.00,28.12,0.00,3.12,3.12,9.38,...,3.12,3.12,0.00,3.12,3.12,0.00,9.38,3.12,3.12,0.0770
3,12.12,6.06,3.03,3.03,6.06,3.03,3.03,3.03,12.12,18.18,...,6.06,0.00,3.03,0.00,12.12,9.09,0.00,0.00,0.00,0.0711
4,2.78,16.67,2.78,0.00,2.78,11.11,2.78,5.56,11.11,5.56,...,2.78,11.11,2.78,5.56,0.00,8.33,5.56,0.00,2.78,0.0647
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,14.29,7.14,7.14,0.00,0.00,10.71,0.00,0.00,17.86,21.43,...,3.57,0.00,0.00,0.00,3.57,3.57,10.71,0.00,0.00,0.0877
227,12.50,8.33,0.00,0.00,12.50,4.17,0.00,4.17,16.67,20.83,...,4.17,8.33,0.00,0.00,0.00,4.17,0.00,0.00,0.00,0.0668
228,3.23,9.68,0.00,0.00,0.00,12.90,0.00,6.45,19.35,6.45,...,3.23,0.00,0.00,0.00,12.90,12.90,9.68,0.00,3.23,0.0750
229,13.04,0.00,4.35,4.35,0.00,17.39,0.00,13.04,13.04,8.70,...,4.35,0.00,4.35,0.00,8.70,0.00,4.35,4.35,0.00,0.0955
230,16.22,5.41,0.00,5.41,5.41,18.92,0.00,8.11,18.92,13.51,...,0.00,0.00,2.70,0.00,2.70,0.00,2.70,0.00,0.00,0.1009

In [ ]:
from Pfeature.pfeature import paac_wp

def paac(input):
  a = input.rstrip('txt')
  output = a + 'paac_2.csv'
  df_out = paac_wp(input, output, 3, 0.05)
  df_in = pd.read_csv(output)
  return df_in

paac('/content/Combined_Pos_cdhit.txt')

,PAAC3_A,PAAC3_C,PAAC3_D,PAAC3_E,PAAC3_F,PAAC3_G,PAAC3_H,PAAC3_I,PAAC3_K,PAAC3_L,...,PAAC3_Q,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0895,0.0967,0.0551
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0853,0.0970,0.0558
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0875,0.0986,0.0527
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0875,0.0971,0.0574
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0855,0.0990,0.0551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,23.08,0.0,0.0,0.0,7.69,0.0,0.00,0.00,30.77,38.46,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0892,0.1255,0.0721
399,0.00,0.0,0.0,0.0,0.00,0.0,0.00,7.69,7.69,7.69,...,0.0,15.38,0.00,0.00,0.00,38.46,0.0,0.1216,0.0869,0.1172
400,27.27,0.0,0.0,0.0,0.00,0.0,0.00,0.00,27.27,36.36,...,0.0,0.00,0.00,0.00,9.09,0.00,0.0,0.0836,0.0970,0.0477
401,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0940,0.1169,0.0795
402,23.08,0.0,0.0,0.0,15.38,0.0,0.00,0.00,30.77,30.77,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0926,0.1274,0.0731

In [ ]:
#feature extraction of PAAC_Data

Bre = '/content/Breast_train_main_cdhit.txt'
Cer = '/content/Cervix_train_main_cdhit.txt'
Col = '/content/Colon_train_main_cdhit.txt'
Lun = '/content/Lungs_train_main_cdhit.txt'
Pro = '/content/Prostate_train_main_cdhit.txt'
Ski = '/content/skin_train_main_cdhit.txt'

def feature_calc(Bre, Cer, Col, Lun, Pro, Ski, feature_name):
  # Calculate cancer feature
  Bre_feature = feature_name(Bre)
  Cer_feature = feature_name(Cer)
  Col_feature = feature_name(Col)
  Lun_feature = feature_name(Lun)
  Pro_feature = feature_name(Pro)
  Ski_feature = feature_name(Ski)
 
  Bre_Cer_Col_Lun_Pro_Ski_neg_feature = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature], axis=0)
 
  # Combine feature and class
  df = pd.concat([Bre_feature, Cer_feature, Col_feature, Lun_feature, Pro_feature, Ski_feature], join="inner")
  return df

feature = feature_calc(Bre, Cer, Col, Lun, Pro, Ski, paac) #PCP
feature

,PAAC3_A,PAAC3_C,PAAC3_D,PAAC3_E,PAAC3_F,PAAC3_G,PAAC3_H,PAAC3_I,PAAC3_K,PAAC3_L,...,PAAC3_Q,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0895,0.0967,0.0551
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0853,0.0970,0.0558
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0875,0.0986,0.0527
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0875,0.0971,0.0574
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,...,0.0,0.00,15.38,11.54,3.85,3.85,0.0,0.0855,0.0990,0.0551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,23.08,0.0,0.0,0.0,7.69,0.0,0.00,0.00,30.77,38.46,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0892,0.1255,0.0721
51,0.00,0.0,0.0,0.0,0.00,0.0,0.00,7.69,7.69,7.69,...,0.0,15.38,0.00,0.00,0.00,38.46,0.0,0.1216,0.0869,0.1172
52,27.27,0.0,0.0,0.0,0.00,0.0,0.00,0.00,27.27,36.36,...,0.0,0.00,0.00,0.00,9.09,0.00,0.0,0.0836,0.0970,0.0477
53,28.57,0.0,0.0,0.0,14.29,0.0,0.00,0.00,28.57,28.57,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0940,0.1169,0.0795
54,23.08,0.0,0.0,0.0,15.38,0.0,0.00,0.00,30.77,30.77,...,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0926,0.1274,0.0731

In [ ]:
from Pfeature.pfeature import paac_wp

def paac(input):
  a = input.rstrip('txt')
  output = a + 'paac_2.csv'
  df_out = paac_wp(input, output, 3, 0.05)
  df_in = pd.read_csv(output)
  return df_in

paac('/content/neg_train_main_cdhit.txt')

,PAAC3_A,PAAC3_C,PAAC3_D,PAAC3_E,PAAC3_F,PAAC3_G,PAAC3_H,PAAC3_I,PAAC3_K,PAAC3_L,...,PAAC3_Q,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3
0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,38.46,53.85,...,0.00,0.00,0.00,0.00,0.00,7.69,0.00,0.1066,0.1304,0.0640
1,9.09,6.06,6.06,0.00,9.09,3.03,0.00,12.12,15.15,6.06,...,0.00,0.00,9.09,9.09,6.06,0.00,0.00,0.0736,0.0858,0.0592
2,25.00,3.12,0.00,0.00,0.00,28.12,0.00,3.12,3.12,9.38,...,0.00,3.12,3.12,0.00,9.38,3.12,3.12,0.0677,0.0661,0.0544
3,12.12,6.06,3.03,3.03,6.06,3.03,3.03,3.03,12.12,18.18,...,3.03,0.00,12.12,9.09,0.00,0.00,0.00,0.0620,0.0738,0.0544
4,2.78,16.67,2.78,0.00,2.78,11.11,2.78,5.56,11.11,5.56,...,2.78,5.56,0.00,8.33,5.56,0.00,2.78,0.0560,0.0762,0.0576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,14.29,7.14,7.14,0.00,0.00,10.71,0.00,0.00,17.86,21.43,...,0.00,0.00,3.57,3.57,10.71,0.00,0.00,0.0751,0.0715,0.0715
227,12.50,8.33,0.00,0.00,12.50,4.17,0.00,4.17,16.67,20.83,...,0.00,0.00,0.00,4.17,0.00,0.00,0.00,0.0576,0.0815,0.0558
228,3.23,9.68,0.00,0.00,0.00,12.90,0.00,6.45,19.35,6.45,...,0.00,0.00,12.90,12.90,9.68,0.00,3.23,0.0652,0.0670,0.0638
229,13.04,0.00,4.35,4.35,0.00,17.39,0.00,13.04,13.04,8.70,...,4.35,0.00,8.70,0.00,4.35,4.35,0.00,0.0808,0.0925,0.0615
230,16.22,5.41,0.00,5.41,5.41,18.92,0.00,8.11,18.92,13.51,...,2.70,0.00,2.70,0.00,2.70,0.00,0.00,0.0838,0.0959,0.0742

In [ ]:
pos= pd.read_csv("/content/Combined_Pos_cdhit.paac_2.csv")
neg=pd.read_csv("/content/neg_train_main_cdhit.paac_2.csv")
paac_data = pd.concat([pos,neg], join="inner")
paac_data

paac_data.to_csv(r"/content/paac_data.csv", index=False)

Amino Acid Index Composition (AAI)

In [ ]:
#from Pfeature.pfeature import aai_wp

#def aai(input):
#  a = input.rstrip('txt')
#  output = a + 'aai.csv'
#  df_out = aai_wp(input, output)
#  df_in = pd.read_csv(output)
#  return df_in

#aai('/content/Combined_Pos_cdhit.txt')

Combining Data

In [ ]:
Br_aac= pd.read_csv("/content/Breast_train_main_cdhit.aac.csv")
Br_dpc = pd.read_csv("/content/Breast_train_main_cdhit.dpc.csv")

Br_aac.head()

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,AAC_M,AAC_N,AAC_P,AAC_Q,AAC_R,AAC_S,AAC_T,AAC_V,AAC_W,AAC_Y
0,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
1,19.23,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,3.85,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
2,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
3,15.38,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,7.69,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0
4,11.54,0.0,0.0,0.0,7.69,0.0,3.85,3.85,26.92,11.54,0.0,0.0,0.0,0.0,0.0,15.38,11.54,3.85,3.85,0.0

In [ ]:
df = pd.concat([Br_aac, Br_dpc], axis=1)
df

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,DPC1_YM,DPC1_YN,DPC1_YP,DPC1_YQ,DPC1_YR,DPC1_YS,DPC1_YT,DPC1_YV,DPC1_YW,DPC1_YY
0,19.23,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,19.23,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,3.85,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,15.38,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,15.38,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,7.69,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,11.54,0.0,0.0,0.00,7.69,0.0,3.85,3.85,26.92,11.54,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,23.08,0.0,0.0,0.00,23.08,0.0,0.00,0.00,30.77,23.08,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
70,23.08,0.0,0.0,0.00,7.69,0.0,0.00,0.00,30.77,30.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71,23.08,0.0,0.0,0.00,7.69,0.0,0.00,7.69,30.77,30.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,23.08,0.0,0.0,7.69,7.69,0.0,0.00,0.00,30.77,30.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,23.08,0.0,0.0,0.00,7.69,0.0,0.00,0.00,30.77,30.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
aac= pd.read_csv("/content/aac_data.csv")
dpc=pd.read_csv("/content/dpc_data.csv")
pcp=pd.read_csv("/content/pcp_data.csv")
paac=pd.read_csv("/content/paac_data.csv")
result = pd.concat([aac,dpc,pcp,paac], axis=1)
result

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PAAC3_Q,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3
0,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,...,0.00,0.0,15.38,11.54,3.85,3.85,0.00,0.0895,0.0967,0.0551
1,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,...,0.00,0.0,15.38,11.54,3.85,3.85,0.00,0.0853,0.0970,0.0558
2,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,...,0.00,0.0,15.38,11.54,3.85,3.85,0.00,0.0875,0.0986,0.0527
3,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,...,0.00,0.0,15.38,11.54,3.85,3.85,0.00,0.0875,0.0971,0.0574
4,11.54,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,11.54,...,0.00,0.0,15.38,11.54,3.85,3.85,0.00,0.0855,0.0990,0.0551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,14.29,7.14,7.14,0.00,0.00,10.71,0.00,0.00,17.86,21.43,...,0.00,0.0,3.57,3.57,10.71,0.00,0.00,0.0751,0.0715,0.0715
630,12.50,8.33,0.00,0.00,12.50,4.17,0.00,4.17,16.67,20.83,...,0.00,0.0,0.00,4.17,0.00,0.00,0.00,0.0576,0.0815,0.0558
631,3.23,9.68,0.00,0.00,0.00,12.90,0.00,6.45,19.35,6.45,...,0.00,0.0,12.90,12.90,9.68,0.00,3.23,0.0652,0.0670,0.0638
632,13.04,0.00,4.35,4.35,0.00,17.39,0.00,13.04,13.04,8.70,...,4.35,0.0,8.70,0.00,4.35,4.35,0.00,0.0808,0.0925,0.0615
633,16.22,5.41,0.00,5.41,5.41,18.92,0.00,8.11,18.92,13.51,...,2.70,0.0,2.70,0.00,2.70,0.00,0.00,0.0838,0.0959,0.0742

In [ ]:
aac.shape

(634, 20)

In [ ]:
dpc.shape

(634, 400)

In [ ]:
paac.shape

(634, 23)

In [ ]:
pcp.shape

(634, 30)

In [ ]:
result.to_csv(r"/content/result.csv", index=False)

In [ ]:
result = pd.read_csv("/content/result.csv")
Tissue = pd.read_csv("/content/Tissue.csv")

In [ ]:
#finalresult = pd.concat([result, ACP_Dataset_dpc[['Tissue']]], axis = 1)

In [ ]:
Finalresult = pd.concat([result, Tissue], axis=1)

Finalresult

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3,Tissue
0,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,...,0.0,15.38,11.54,3.85,3.85,0.00,0.0895,0.0967,0.0551,Breast
1,19.23,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,3.85,...,0.0,15.38,11.54,3.85,3.85,0.00,0.0853,0.0970,0.0558,Breast
2,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,...,0.0,15.38,11.54,3.85,3.85,0.00,0.0875,0.0986,0.0527,Breast
3,15.38,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,7.69,...,0.0,15.38,11.54,3.85,3.85,0.00,0.0875,0.0971,0.0574,Breast
4,11.54,0.00,0.00,0.00,7.69,0.00,3.85,3.85,26.92,11.54,...,0.0,15.38,11.54,3.85,3.85,0.00,0.0855,0.0990,0.0551,Breast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,14.29,7.14,7.14,0.00,0.00,10.71,0.00,0.00,17.86,21.43,...,0.0,3.57,3.57,10.71,0.00,0.00,0.0751,0.0715,0.0715,Negative
630,12.50,8.33,0.00,0.00,12.50,4.17,0.00,4.17,16.67,20.83,...,0.0,0.00,4.17,0.00,0.00,0.00,0.0576,0.0815,0.0558,Negative
631,3.23,9.68,0.00,0.00,0.00,12.90,0.00,6.45,19.35,6.45,...,0.0,12.90,12.90,9.68,0.00,3.23,0.0652,0.0670,0.0638,Negative
632,13.04,0.00,4.35,4.35,0.00,17.39,0.00,13.04,13.04,8.70,...,0.0,8.70,0.00,4.35,4.35,0.00,0.0808,0.0925,0.0615,Negative
633,16.22,5.41,0.00,5.41,5.41,18.92,0.00,8.11,18.92,13.51,...,0.0,2.70,0.00,2.70,0.00,0.00,0.0838,0.0959,0.0742,Negative

In [ ]:
Finalresult.to_csv(r"/content/Finalresult.csv", index=False)

Principal Component Analysis

In [ ]:
from sklearn.preprocessing import StandardScaler

#load the data into pandas dataframe
df = pd.read_csv("/content/Finalresult.csv") #names=['AAC_A', 'AAC_A', 'AAC_C','AAC_D','AAC_E','AAC_F','AAC_G','AAC_H','AAC_I','AAC_K','AAC_L','AAC_M','AAC_N','AAC_P','AAC_Q','AAC_R','AAC_S','AAC_T','AAC_V','AAC_W','AAC_Y','DPC1_AA','DPC1_AC','DPC1_AD','DPC1_AE','DPC1_AF','DPC1_AG','DPC1_AH','DPC1_AI','DPC1_AK','DPC1_AL','DPC1_AM','DPC1_AN','DPC1_AP','DPC1_AQ','DPC1_AR','DPC1_AS','DPC1_AT','DPC1_AV','DPC1_AW','DPC1_AY','DPC1_CA','DPC1_CC','DPC1_CD','DPC1_CE','DPC1_CF','DPC1_CG','DPC1_CH','DPC1_CI','DPC1_CK','DPC1_CL','DPC1_CM','DPC1_CN','DPC1_CP','DPC1_CQ','DPC1_CR','DPC1_CS','DPC1_CT','DPC1_CV','DPC1_CW','DPC1_CY','DPC1_DA','DPC1_DC','DPC1_DD','DPC1_DE','DPC1_DF','DPC1_DG','DPC1_DH','DPC1_DI','DPC1_DK','DPC1_DL','DPC1_DM','DPC1_DN','DPC1_DP','DPC1_DQ','DPC1_DR','DPC1_DS','DPC1_DT','DPC1_DV','DPC1_DW','DPC1_DY','DPC1_EA','DPC1_EC','DPC1_ED','DPC1_EE','DPC1_EF','DPC1_EG','DPC1_EH','DPC1_EI','DPC1_EK','DPC1_EL','DPC1_EM','DPC1_EN','DPC1_EP','DPC1_EQ','DPC1_ER','DPC1_ES','DPC1_ET','DPC1_EV','DPC1_EW','DPC1_EY','DPC1_FA','DPC1_FC','DPC1_FD','DPC1_FE','DPC1_FF','DPC1_FG','DPC1_FH','DPC1_FI','DPC1_FK','DPC1_FL','DPC1_FM','DPC1_FN','DPC1_FP','DPC1_FQ','DPC1_FR','DPC1_FS','DPC1_FT','DPC1_FV','DPC1_FW','DPC1_FY','DPC1_GA','DPC1_GC','DPC1_GD','DPC1_GE','DPC1_GF','DPC1_GG','DPC1_GH','DPC1_GI','DPC1_GK','DPC1_GL','DPC1_GM','DPC1_GN','DPC1_GP','DPC1_GQ','DPC1_GR','DPC1_GS','DPC1_GT','DPC1_GV','DPC1_GW','DPC1_GY','DPC1_HA','DPC1_HC','DPC1_HD','DPC1_HE','DPC1_HF','DPC1_HG','DPC1_HH','DPC1_HI','DPC1_HK','DPC1_HL','DPC1_HM','DPC1_HN','DPC1_HP','DPC1_HQ','DPC1_HR','DPC1_HS','DPC1_HT','DPC1_HV','DPC1_HW','DPC1_HY','DPC1_IA','DPC1_IC','DPC1_ID','DPC1_IE','DPC1_IF','DPC1_IG','DPC1_IH','DPC1_II','DPC1_IK','DPC1_IL','DPC1_IM','DPC1_IN','DPC1_IP','DPC1_IQ','DPC1_IR','DPC1_IS','DPC1_IT','DPC1_IV','DPC1_IW','DPC1_IY','DPC1_KA','DPC1_KC','DPC1_KD','DPC1_KE','DPC1_KF','DPC1_KG','DPC1_KH','DPC1_KI','DPC1_KK','DPC1_KL','DPC1_KM','DPC1_KN','DPC1_KP','DPC1_KQ','DPC1_KR','DPC1_KS','DPC1_KT','DPC1_KV','DPC1_KW','DPC1_KY','DPC1_LA','DPC1_LC','DPC1_LD','DPC1_LE','DPC1_LF','DPC1_LG','DPC1_LH','DPC1_LI','DPC1_LK','DPC1_LL','DPC1_LM','DPC1_LN','DPC1_LP','DPC1_LQ','DPC1_LR','DPC1_LS','DPC1_LT','DPC1_LV','DPC1_LW','DPC1_LY','DPC1_MA','DPC1_MC','DPC1_MD','DPC1_ME','DPC1_MF','DPC1_MG','DPC1_MH','DPC1_MI','DPC1_MK','DPC1_ML','DPC1_MM','DPC1_MN','DPC1_MP','DPC1_MQ','DPC1_MR','DPC1_MS','DPC1_MT','DPC1_MV','DPC1_MW','DPC1_MY','DPC1_NA','DPC1_NC','DPC1_ND','DPC1_NE','DPC1_NF','DPC1_NG','DPC1_NH','DPC1_NI','DPC1_NK','DPC1_NL','DPC1_NM','DPC1_NN','DPC1_NP','DPC1_NQ','DPC1_NR','DPC1_NS','DPC1_NT','DPC1_NV','DPC1_NW','DPC1_NY','DPC1_PA','DPC1_PC','DPC1_PD','DPC1_PE','DPC1_PF','DPC1_PG','DPC1_PH','DPC1_PI','DPC1_PK','DPC1_PL','DPC1_PM','DPC1_PN','DPC1_PP','DPC1_PQ','DPC1_PR','DPC1_PS','DPC1_PT','DPC1_PV','DPC1_PW','DPC1_PY','DPC1_QA','DPC1_QC','DPC1_QD','DPC1_QE','DPC1_QF','DPC1_QG','DPC1_QH','DPC1_QI','DPC1_QK','DPC1_QL','DPC1_QM','DPC1_QN','DPC1_QP','DPC1_QQ','DPC1_QR','DPC1_QS','DPC1_QT','DPC1_QV','DPC1_QW','DPC1_QY','DPC1_RA','DPC1_RC','DPC1_RD','DPC1_RE','DPC1_RF','DPC1_RG','DPC1_RH','DPC1_RI','DPC1_RK','DPC1_RL','DPC1_RM','DPC1_RN','DPC1_RP','DPC1_RQ','DPC1_RR','DPC1_RS','DPC1_RT','DPC1_RV','DPC1_RW','DPC1_RY','DPC1_SA','DPC1_SC','DPC1_SD','DPC1_SE','DPC1_SF','DPC1_SG','DPC1_SH','DPC1_SI','DPC1_SK','DPC1_SL','DPC1_SM','DPC1_SN','DPC1_SP','DPC1_SQ','DPC1_SR','DPC1_SS','DPC1_ST','DPC1_SV','DPC1_SW','DPC1_SY','DPC1_TA','DPC1_TC','DPC1_TD','DPC1_TE','DPC1_TF','DPC1_TG','DPC1_TH','DPC1_TI','DPC1_TK','DPC1_TL','DPC1_TM','DPC1_TN','DPC1_TP','DPC1_TQ','DPC1_TR','DPC1_TS','DPC1_TT','DPC1_TV','DPC1_TW','DPC1_TY','DPC1_VA','DPC1_VC','DPC1_VD','DPC1_VE','DPC1_VF','DPC1_VG','DPC1_VH','DPC1_VI','DPC1_VK','DPC1_VL','DPC1_VM','DPC1_VN','DPC1_VP','DPC1_VQ','DPC1_VR','DPC1_VS','DPC1_VT','DPC1_VV','DPC1_VW','DPC1_VY','DPC1_WA','DPC1_WC','DPC1_WD','DPC1_WE','DPC1_WF','DPC1_WG','DPC1_WH','DPC1_WI','DPC1_WK','DPC1_WL','DPC1_WM','DPC1_WN','DPC1_WP','DPC1_WQ','DPC1_WR','DPC1_WS','DPC1_WT','DPC1_WV','DPC1_WW','DPC1_WY','DPC1_YA','DPC1_YC','DPC1_YD','DPC1_YE','DPC1_YF','DPC1_YG','DPC1_YH','DPC1_YI','DPC1_YK','DPC1_YL','DPC1_YM','DPC1_YN','DPC1_YP','DPC1_YQ','DPC1_YR','DPC1_YS','DPC1_YT','DPC1_YV','DPC1_YW','DPC1_YY','PCP_PC','PCP_NC','PCP_NE','PCP_PO','PCP_NP','PCP_AL','PCP_CY','PCP_AR','PCP_AC','PCP_BS','PCP_NE_pH','PCP_HB','PCP_HL','PCP_NT','PCP_HX','PCP_SC','PCP_SS_HE','PCP_SS_ST','PCP_SS_CO','PCP_SA_BU','PCP_SA_EX','PCP_SA_IN','PCP_TN','PCP_SM','PCP_LR','PCP_Z1','PCP_Z2','PCP_Z3','PCP_Z4','PCP_Z5','PAAC3_A','PAAC3_C','PAAC3_D','PAAC3_E','PAAC3_F','PAAC3_G','PAAC3_H','PAAC3_I','PAAC3_K','PAAC3_L','PAAC3_M','PAAC3_N','PAAC3_P','PAAC3_Q','PAAC3_R','PAAC3_S','PAAC3_T','PAAC3_V','PAAC3_W','PAAC3_Y','PAAC3_lam1','PAAC3_lam2','PAAC3_lam3','Tissue'])

#Standarizing the data
features = ['AAC_A', 'AAC_C','AAC_D','AAC_E','AAC_F','AAC_G','AAC_H','AAC_I','AAC_K','AAC_L','AAC_M','AAC_N','AAC_P','AAC_Q','AAC_R','AAC_S','AAC_T','AAC_V','AAC_W','AAC_Y','DPC1_AA','DPC1_AC','DPC1_AD','DPC1_AE','DPC1_AF','DPC1_AG','DPC1_AH','DPC1_AI','DPC1_AK','DPC1_AL','DPC1_AM','DPC1_AN','DPC1_AP','DPC1_AQ','DPC1_AR','DPC1_AS','DPC1_AT','DPC1_AV','DPC1_AW','DPC1_AY','DPC1_CA','DPC1_CC','DPC1_CD','DPC1_CE','DPC1_CF','DPC1_CG','DPC1_CH','DPC1_CI','DPC1_CK','DPC1_CL','DPC1_CM','DPC1_CN','DPC1_CP','DPC1_CQ','DPC1_CR','DPC1_CS','DPC1_CT','DPC1_CV','DPC1_CW','DPC1_CY','DPC1_DA','DPC1_DC','DPC1_DD','DPC1_DE','DPC1_DF','DPC1_DG','DPC1_DH','DPC1_DI','DPC1_DK','DPC1_DL','DPC1_DM','DPC1_DN','DPC1_DP','DPC1_DQ','DPC1_DR','DPC1_DS','DPC1_DT','DPC1_DV','DPC1_DW','DPC1_DY','DPC1_EA','DPC1_EC','DPC1_ED','DPC1_EE','DPC1_EF','DPC1_EG','DPC1_EH','DPC1_EI','DPC1_EK','DPC1_EL','DPC1_EM','DPC1_EN','DPC1_EP','DPC1_EQ','DPC1_ER','DPC1_ES','DPC1_ET','DPC1_EV','DPC1_EW','DPC1_EY','DPC1_FA','DPC1_FC','DPC1_FD','DPC1_FE','DPC1_FF','DPC1_FG','DPC1_FH','DPC1_FI','DPC1_FK','DPC1_FL','DPC1_FM','DPC1_FN','DPC1_FP','DPC1_FQ','DPC1_FR','DPC1_FS','DPC1_FT','DPC1_FV','DPC1_FW','DPC1_FY','DPC1_GA','DPC1_GC','DPC1_GD','DPC1_GE','DPC1_GF','DPC1_GG','DPC1_GH','DPC1_GI','DPC1_GK','DPC1_GL','DPC1_GM','DPC1_GN','DPC1_GP','DPC1_GQ','DPC1_GR','DPC1_GS','DPC1_GT','DPC1_GV','DPC1_GW','DPC1_GY','DPC1_HA','DPC1_HC','DPC1_HD','DPC1_HE','DPC1_HF','DPC1_HG','DPC1_HH','DPC1_HI','DPC1_HK','DPC1_HL','DPC1_HM','DPC1_HN','DPC1_HP','DPC1_HQ','DPC1_HR','DPC1_HS','DPC1_HT','DPC1_HV','DPC1_HW','DPC1_HY','DPC1_IA','DPC1_IC','DPC1_ID','DPC1_IE','DPC1_IF','DPC1_IG','DPC1_IH','DPC1_II','DPC1_IK','DPC1_IL','DPC1_IM','DPC1_IN','DPC1_IP','DPC1_IQ','DPC1_IR','DPC1_IS','DPC1_IT','DPC1_IV','DPC1_IW','DPC1_IY','DPC1_KA','DPC1_KC','DPC1_KD','DPC1_KE','DPC1_KF','DPC1_KG','DPC1_KH','DPC1_KI','DPC1_KK','DPC1_KL','DPC1_KM','DPC1_KN','DPC1_KP','DPC1_KQ','DPC1_KR','DPC1_KS','DPC1_KT','DPC1_KV','DPC1_KW','DPC1_KY','DPC1_LA','DPC1_LC','DPC1_LD','DPC1_LE','DPC1_LF','DPC1_LG','DPC1_LH','DPC1_LI','DPC1_LK','DPC1_LL','DPC1_LM','DPC1_LN','DPC1_LP','DPC1_LQ','DPC1_LR','DPC1_LS','DPC1_LT','DPC1_LV','DPC1_LW','DPC1_LY','DPC1_MA','DPC1_MC','DPC1_MD','DPC1_ME','DPC1_MF','DPC1_MG','DPC1_MH','DPC1_MI','DPC1_MK','DPC1_ML','DPC1_MM','DPC1_MN','DPC1_MP','DPC1_MQ','DPC1_MR','DPC1_MS','DPC1_MT','DPC1_MV','DPC1_MW','DPC1_MY','DPC1_NA','DPC1_NC','DPC1_ND','DPC1_NE','DPC1_NF','DPC1_NG','DPC1_NH','DPC1_NI','DPC1_NK','DPC1_NL','DPC1_NM','DPC1_NN','DPC1_NP','DPC1_NQ','DPC1_NR','DPC1_NS','DPC1_NT','DPC1_NV','DPC1_NW','DPC1_NY','DPC1_PA','DPC1_PC','DPC1_PD','DPC1_PE','DPC1_PF','DPC1_PG','DPC1_PH','DPC1_PI','DPC1_PK','DPC1_PL','DPC1_PM','DPC1_PN','DPC1_PP','DPC1_PQ','DPC1_PR','DPC1_PS','DPC1_PT','DPC1_PV','DPC1_PW','DPC1_PY','DPC1_QA','DPC1_QC','DPC1_QD','DPC1_QE','DPC1_QF','DPC1_QG','DPC1_QH','DPC1_QI','DPC1_QK','DPC1_QL','DPC1_QM','DPC1_QN','DPC1_QP','DPC1_QQ','DPC1_QR','DPC1_QS','DPC1_QT','DPC1_QV','DPC1_QW','DPC1_QY','DPC1_RA','DPC1_RC','DPC1_RD','DPC1_RE','DPC1_RF','DPC1_RG','DPC1_RH','DPC1_RI','DPC1_RK','DPC1_RL','DPC1_RM','DPC1_RN','DPC1_RP','DPC1_RQ','DPC1_RR','DPC1_RS','DPC1_RT','DPC1_RV','DPC1_RW','DPC1_RY','DPC1_SA','DPC1_SC','DPC1_SD','DPC1_SE','DPC1_SF','DPC1_SG','DPC1_SH','DPC1_SI','DPC1_SK','DPC1_SL','DPC1_SM','DPC1_SN','DPC1_SP','DPC1_SQ','DPC1_SR','DPC1_SS','DPC1_ST','DPC1_SV','DPC1_SW','DPC1_SY','DPC1_TA','DPC1_TC','DPC1_TD','DPC1_TE','DPC1_TF','DPC1_TG','DPC1_TH','DPC1_TI','DPC1_TK','DPC1_TL','DPC1_TM','DPC1_TN','DPC1_TP','DPC1_TQ','DPC1_TR','DPC1_TS','DPC1_TT','DPC1_TV','DPC1_TW','DPC1_TY','DPC1_VA','DPC1_VC','DPC1_VD','DPC1_VE','DPC1_VF','DPC1_VG','DPC1_VH','DPC1_VI','DPC1_VK','DPC1_VL','DPC1_VM','DPC1_VN','DPC1_VP','DPC1_VQ','DPC1_VR','DPC1_VS','DPC1_VT','DPC1_VV','DPC1_VW','DPC1_VY','DPC1_WA','DPC1_WC','DPC1_WD','DPC1_WE','DPC1_WF','DPC1_WG','DPC1_WH','DPC1_WI','DPC1_WK','DPC1_WL','DPC1_WM','DPC1_WN','DPC1_WP','DPC1_WQ','DPC1_WR','DPC1_WS','DPC1_WT','DPC1_WV','DPC1_WW','DPC1_WY','DPC1_YA','DPC1_YC','DPC1_YD','DPC1_YE','DPC1_YF','DPC1_YG','DPC1_YH','DPC1_YI','DPC1_YK','DPC1_YL','DPC1_YM','DPC1_YN','DPC1_YP','DPC1_YQ','DPC1_YR','DPC1_YS','DPC1_YT','DPC1_YV','DPC1_YW','DPC1_YY','PCP_PC','PCP_NC','PCP_NE','PCP_PO','PCP_NP','PCP_AL','PCP_CY','PCP_AR','PCP_AC','PCP_BS','PCP_NE_pH','PCP_HB','PCP_HL','PCP_NT','PCP_HX','PCP_SC','PCP_SS_HE','PCP_SS_ST','PCP_SS_CO','PCP_SA_BU','PCP_SA_EX','PCP_SA_IN','PCP_TN','PCP_SM','PCP_LR','PCP_Z1','PCP_Z2','PCP_Z3','PCP_Z4','PCP_Z5','PAAC3_A','PAAC3_C','PAAC3_D','PAAC3_E','PAAC3_F','PAAC3_G','PAAC3_H','PAAC3_I','PAAC3_K','PAAC3_L','PAAC3_M','PAAC3_N','PAAC3_P','PAAC3_Q','PAAC3_R','PAAC3_S','PAAC3_T','PAAC3_V','PAAC3_W','PAAC3_Y','PAAC3_lam1','PAAC3_lam2','PAAC3_lam3']

#separating out the features
x = df.loc[:, features].values

#separting out the target
y = df.loc[:, ['Tissue']].values

#Standardizing the features
x = StandardScaler().fit_transform(x)

In [ ]:
x = pd.DataFrame(data = x, columns = features)

In [ ]:
x

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PAAC3_Q,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3
0,0.331276,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-1.214501,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,0.138224,-0.256172,-0.928222
1,0.331276,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-1.214501,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,-0.094345,-0.244362,-0.888559
2,-0.015155,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-0.900447,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,0.027477,-0.181373,-1.064210
3,-0.015155,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-0.900447,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,0.027477,-0.240425,-0.797901
4,-0.360687,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-0.585576,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,-0.083270,-0.165626,-0.928222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,-0.113236,0.776318,2.373135,-0.397775,-1.168877,0.775722,-0.448726,-0.692714,-0.433148,0.223276,...,-0.352096,-0.468018,0.043265,0.264739,1.359805,-0.383267,-0.378866,-0.659154,-1.248249,0.001028
630,-0.274304,0.984594,-0.434951,-0.397775,1.272593,-0.155487,-0.448726,-0.021755,-0.522386,0.174206,...,-0.352096,-0.468018,-0.655805,0.406545,-0.747241,-0.383267,-0.378866,-1.628189,-0.854568,-0.888559
631,-1.108439,1.220874,-0.434951,-0.397775,-1.168877,1.087549,-0.448726,0.345101,-0.321413,-1.001860,...,-0.352096,-0.468018,1.870247,2.469830,1.157166,-0.383267,0.978201,-1.207351,-1.425405,-0.435266
632,-0.225713,-0.473337,1.275858,0.993964,-1.168877,1.726865,-0.448726,1.405441,-0.794600,-0.817844,...,1.324084,-0.468018,1.047812,-0.579010,0.108562,0.473029,-0.378866,-0.343525,-0.421518,-0.565588
633,0.060430,0.473531,-0.434951,1.333101,-0.112209,1.944716,-0.448726,0.612197,-0.353658,-0.424459,...,0.688292,-0.468018,-0.127096,-0.579010,-0.216053,-0.383267,-0.378866,-0.177405,-0.287667,0.154014

In [ ]:
#from sklearn.feature_selection import VarianceThreshold

#fs = VarianceThreshold(threshold=0.1)
#fs.fit_transform(x)

#X2.shape
#X2= x[:, fs.get_support(indices=False)]
#X2

In [ ]:
#X2.shape

In [ ]:
#pd.DataFrame(data=X2)

In [ ]:
#pca projection to 2d
#import pandas as pd
#from sklearn.decomposition import PCA

#pca = PCA(n_components=5)
#pca = PCA(.95)

#principalComponents
#principalComponents = pca.fit_transform(x)
#pca.fit(X2)
#pca.n_components_

In [ ]:
#PrincipalComponent = pca.transform(X2)
#PrincipalComponent

In [ ]:
#PrincipalDF = pd.DataFrame(data = PrincipalComponent, columns = ['PC 1', 'PC 2', 'PC 3', 'PC 4', 'PC 5', 'PC 6', 'PC 7', 'PC 8','PC 9', 'PC 10', 'PC 11', 'PC 12 ', 'PC 13', 'PC 14', 'PC 15', 'PC 16', 'PC 17', 'PC 18', 'PC 19', 'PC 20', 'PC 21', 'PC 22', 'PC 23', 'PC 24', 'PC 25', 'PC 26', 'PC 27', 'PC 28', 'PC 29', 'PC 30', 'PC 31','PC 32','PC 33','PC 34','PC 35','PC 36','PC 37','PC 38','PC 39','PC 40','PC 41','PC 42','PC 43','PC 44','PC 45','PC 46','PC 47','PC 48','PC 49','PC 50','PC 51','PC 52','PC 53','PC 54','PC 55','PC 56','PC 57','PC 58','PC 59','PC 60','PC 61','PC 62','PC 63','PC 64','PC 65','PC 66','PC 67','PC 68','PC 69','PC 70','PC 71','PC 72','PC 73','PC 74','PC 75','PC 76','PC 77','PC 78','PC 79','PC 80','PC 81','PC 82','PC 83','PC 84','PC 85','PC 86','PC 87','PC 88','PC 89','PC 90','PC 91','PC 92','PC 93','PC 94','PC 95','PC 96','PC 97','PC 98','PC 99','PC 100','PC 101','PC 102','PC 103','PC 104','PC 105', 'PC 106', 'PC 107', 'PC 108','PC 109', 'PC 110', 'PC 111', 'PC 112 ', 'PC 113', 'PC 114', 'PC 115', 'PC 116', 'PC 117', 'PC 118', 'PC 119', 'PC 120', 'PC 121', 'PC 122', 'PC 123', 'PC 124', 'PC 125', 'PC 126', 'PC 127', 'PC 128', 'PC 129', 'PC 130', 'PC 131','PC 132','PC 133','PC 134','PC 135','PC 136','PC 137','PC 138','PC 139','PC 140','PC 141','PC 142','PC 143','PC 144','PC 145','PC 146','PC 147','PC 148','PC 149','PC 150','PC 151','PC 152','PC 153','PC 154','PC 155','PC 156','PC 157','PC 158','PC 159','PC 160','PC 161','PC 162','PC 163','PC 164','PC 165','PC 166','PC 167','PC 168','PC 169','PC 170','PC 171','PC 172','PC 173','PC 174'])
#PrincipalDF

In [ ]:
#df[['Tissue']].head()

In [ ]:
y

array([['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Breast'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Colon'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Cervix'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Lungs'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Prostate'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Skin'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative'],
       ['Negative']], dtype=object)

In [ ]:
Y = df['Tissue'].copy()

In [ ]:
Y

0        Breast
1        Breast
2        Breast
3        Breast
4        Breast
         ...
629    Negative
630    Negative
631    Negative
632    Negative
633    Negative
Name: Tissue, Length: 634, dtype: object

In [ ]:
#Encoding y class label
Y = Y.map({"Breast": 1, "Colon": 2, "Cervix": 3, "Lungs": 4, "Prostate": 5, "Skin": 6, "Negative": 0})

In [ ]:
#finalDf = pd.concat([PrincipalDF, df[['Tissue']]], axis = 1)
#finalDf.head(5)

In [ ]:
#finalDf.to_csv(r"/content/finalDf")

In [ ]:
#pca.explained_variance_ratio_

In [ ]:
x

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PAAC3_Q,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3
0,0.331276,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-1.214501,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,0.138224,-0.256172,-0.928222
1,0.331276,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-1.214501,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,-0.094345,-0.244362,-0.888559
2,-0.015155,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-0.900447,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,0.027477,-0.181373,-1.064210
3,-0.015155,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-0.900447,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,0.027477,-0.240425,-0.797901
4,-0.360687,-0.473337,-0.434951,-0.397775,0.333115,-0.749239,1.429998,-0.073243,0.246262,-0.585576,...,-0.352096,-0.468018,2.355876,2.148402,0.010194,0.374604,-0.378866,-0.083270,-0.165626,-0.928222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629,-0.113236,0.776318,2.373135,-0.397775,-1.168877,0.775722,-0.448726,-0.692714,-0.433148,0.223276,...,-0.352096,-0.468018,0.043265,0.264739,1.359805,-0.383267,-0.378866,-0.659154,-1.248249,0.001028
630,-0.274304,0.984594,-0.434951,-0.397775,1.272593,-0.155487,-0.448726,-0.021755,-0.522386,0.174206,...,-0.352096,-0.468018,-0.655805,0.406545,-0.747241,-0.383267,-0.378866,-1.628189,-0.854568,-0.888559
631,-1.108439,1.220874,-0.434951,-0.397775,-1.168877,1.087549,-0.448726,0.345101,-0.321413,-1.001860,...,-0.352096,-0.468018,1.870247,2.469830,1.157166,-0.383267,0.978201,-1.207351,-1.425405,-0.435266
632,-0.225713,-0.473337,1.275858,0.993964,-1.168877,1.726865,-0.448726,1.405441,-0.794600,-0.817844,...,1.324084,-0.468018,1.047812,-0.579010,0.108562,0.473029,-0.378866,-0.343525,-0.421518,-0.565588
633,0.060430,0.473531,-0.434951,1.333101,-0.112209,1.944716,-0.448726,0.612197,-0.353658,-0.424459,...,0.688292,-0.468018,-0.127096,-0.579010,-0.216053,-0.383267,-0.378866,-0.177405,-0.287667,0.154014

In [ ]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
629    0
630    0
631    0
632    0
633    0
Name: Tissue, Length: 634, dtype: int64

**Data Splitting**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(x, Y, test_size=0.2, random_state =42, stratify=Y)

In [ ]:
X_train

,AAC_A,AAC_C,AAC_D,AAC_E,AAC_F,AAC_G,AAC_H,AAC_I,AAC_K,AAC_L,...,PAAC3_Q,PAAC3_R,PAAC3_S,PAAC3_T,PAAC3_V,PAAC3_W,PAAC3_Y,PAAC3_lam1,PAAC3_lam2,PAAC3_lam3
34,-0.798900,-0.473337,-0.434951,-0.397775,0.133891,0.200480,-0.448726,0.380499,0.726948,0.106324,...,-0.352096,-0.468018,-0.655805,-0.579010,1.875254,0.929720,-0.378866,1.018662,0.188688,0.018026
480,-1.007659,-0.473337,-0.434951,-0.397775,-1.168877,-0.749239,-0.448726,0.707129,-1.772470,-1.173608,...,3.000263,1.545446,-0.655805,1.477184,-0.747241,-0.383267,6.927447,-0.542870,-1.118334,-0.882893
372,-0.340891,-0.473337,1.877590,-0.397775,-0.020410,1.763885,2.420598,3.093296,-0.890587,-1.048478,...,-0.352096,-0.468018,0.495605,-0.579010,0.409568,-0.383267,-0.378866,-0.991395,0.058773,-0.185955
371,-0.836693,-0.473337,2.023107,-0.397775,0.051858,1.920511,-0.448726,2.324188,-0.835094,-0.507062,...,-0.352096,-0.468018,0.568058,-0.579010,1.711963,-0.383267,-0.378866,-1.019081,-0.142005,-0.446599
132,-1.399082,-0.473337,-0.434951,2.971194,-0.141507,-0.000285,-0.448726,1.001578,-0.193930,-1.099184,...,-0.352096,1.157885,-0.655805,-0.579010,0.287592,-0.383267,-0.378866,0.847004,0.188688,0.193677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,-0.113236,0.776318,2.373135,-0.397775,-0.471593,0.775722,-0.448726,-0.118296,-0.700862,-0.360667,...,-0.352096,-0.468018,0.043265,1.108488,-0.044892,-0.383267,-0.378866,-0.686841,-1.189197,-0.089631
492,-1.399082,0.872580,5.613839,0.833994,-0.416904,-0.201050,-0.448726,-0.073243,-1.772470,-0.271522,...,4.094596,0.126448,0.850035,1.238477,0.765661,-0.383267,-0.378866,-0.991395,-1.594688,-1.273858
344,0.677708,-0.473337,-0.434951,2.062564,0.333115,-0.749239,-0.448726,-0.692714,0.534973,0.987147,...,-0.352096,-0.468018,-0.655805,-0.579010,-0.747241,-0.383267,-0.378866,0.010865,0.397339,0.459987
625,-0.308497,0.587295,0.756716,0.571643,-0.577065,0.113624,-0.448726,-0.205182,-1.090810,-0.042524,...,-0.352096,-0.468018,2.310838,0.853236,0.444981,-0.383267,-0.378866,-1.434382,-1.397848,-1.744149
485,-0.113236,1.192870,-0.434951,-0.397775,-0.239165,2.640987,-0.448726,-0.692714,-1.058565,0.417924,...,-0.352096,-0.468018,1.208382,-0.579010,0.189224,-0.383267,-0.378866,-2.137625,-1.181323,-0.446599

In [ ]:
Y_train

34     1
480    0
372    6
371    6
132    2
      ..
551    0
492    0
344    5
625    0
485    0
Name: Tissue, Length: 507, dtype: int64

**Algorithms**

In [ ]:
#SVC

from sklearn.svm import SVC

# Building a Support Vector Machine on train data
svc_model = SVC(C= .1, kernel='linear', gamma= 1, probability=True)

In [ ]:
svc_model.fit(X_train, Y_train)

SVC(C=0.1, gamma=1, kernel='linear', probability=True)

In [ ]:
#Predict the test set result

prediction = svc_model.predict(X_test)

In [ ]:
X_pred = svc_model.predict(X_train)

In [ ]:
prediction

array([3, 0, 0, 1, 2, 5, 0, 4, 2, 0, 0, 3, 0, 2, 0, 5, 1, 1, 2, 5, 0, 5,
       0, 6, 0, 5, 2, 5, 1, 1, 0, 0, 2, 0, 0, 0, 3, 0, 1, 5, 5, 1, 0, 4,
       4, 1, 0, 1, 0, 5, 0, 4, 0, 1, 4, 0, 2, 3, 0, 0, 5, 1, 4, 5, 2, 3,
       0, 0, 5, 0, 0, 0, 5, 0, 1, 0, 1, 4, 1, 0, 2, 3, 3, 1, 0, 1, 3, 2,
       1, 3, 5, 1, 4, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 3, 0, 0, 1, 1,
       1, 0, 0, 5, 2, 3, 2, 4, 0, 3, 5, 5, 1, 1, 4, 3, 4])

In [ ]:
# check the accuracy on the training set
svc_model.score(X_train, Y_train)

0.6015779092702169

In [ ]:
svc_model.score(X_test, Y_test)

0.3937007874015748

In [ ]:
from sklearn import metrics

In [ ]:
from sklearn.metrics import confusion_matrix

cm="Confusion Matrix:\n",confusion_matrix(prediction,Y_test)
cm

('Confusion Matrix:\n', array([[43,  0,  0,  0,  0,  3,  1],
        [ 0,  1,  6,  7,  7,  3,  2],
        [ 0,  2,  0,  2,  3,  2,  3],
        [ 0,  5,  3,  1,  3,  0,  1],
        [ 0,  4,  3,  2,  0,  1,  1],
        [ 3,  3,  3,  2,  0,  4,  2],
        [ 0,  0,  0,  0,  0,  0,  1]]))

In [ ]:
from sklearn.metrics import accuracy_score 

"Accuracy : ", accuracy_score(Y_test, prediction)

('Accuracy : ', 0.3937007874015748)

In [ ]:
# Matthew Correlation Coefficient
from sklearn.metrics import matthews_corrcoef

"MCC :", matthews_corrcoef(Y_test, prediction)

('MCC :', 0.24078625205611212)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
from sklearn.metrics import roc_curve, auc

In [ ]:
Y_train

34     1
480    0
372    6
371    6
132    2
      ..
551    0
492    0
344    5
625    0
485    0
Name: Tissue, Length: 507, dtype: int64

In [ ]:
X_pred

array([5, 0, 5, 5, 1, 4, 4, 2, 0, 1, 0, 0, 1, 1, 5, 2, 6, 0, 3, 2, 0, 0,
       1, 0, 3, 1, 1, 0, 2, 0, 4, 0, 0, 5, 4, 0, 0, 0, 0, 2, 1, 1, 0, 6,
       0, 0, 1, 0, 0, 0, 3, 0, 3, 1, 0, 3, 6, 0, 3, 0, 2, 0, 0, 2, 0, 4,
       1, 0, 2, 1, 3, 5, 4, 3, 0, 0, 4, 0, 1, 3, 4, 5, 5, 3, 3, 2, 0, 0,
       1, 1, 2, 1, 1, 0, 2, 3, 1, 0, 5, 6, 2, 5, 1, 4, 0, 4, 0, 5, 3, 0,
       0, 0, 0, 2, 0, 0, 0, 3, 4, 0, 1, 5, 0, 5, 5, 3, 3, 4, 0, 5, 4, 3,
       3, 3, 1, 0, 0, 3, 0, 1, 3, 0, 5, 1, 1, 0, 2, 6, 0, 3, 0, 4, 1, 5,
       4, 1, 0, 5, 4, 2, 4, 2, 0, 3, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       3, 0, 4, 0, 0, 2, 0, 0, 0, 0, 0, 4, 1, 0, 3, 3, 0, 2, 1, 1, 0, 0,
       0, 1, 4, 0, 3, 3, 1, 2, 1, 1, 3, 0, 3, 0, 5, 5, 0, 4, 0, 2, 3, 4,
       0, 0, 0, 1, 1, 1, 5, 1, 3, 0, 1, 5, 0, 0, 3, 1, 3, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 2, 2, 5, 4, 5, 1, 5, 0, 2, 3, 0, 6, 0, 3, 4, 0, 3,
       0, 0, 0, 2, 1, 0, 5, 2, 0, 1, 1, 3, 1, 5, 1, 5, 3, 0, 0, 0, 2, 1,
       1, 5, 0, 6, 0, 0, 3, 2, 5, 2, 3, 3, 0, 0, 1, 0, 5, 0, 2, 4, 5, 1,
       1, 3, 0, 2, 0, 0, 3, 5, 0, 6, 0, 1, 0, 0, 5, 3, 4, 4, 1, 1, 1, 1,
       3, 0, 0, 0, 4, 1, 1, 1, 0, 1, 3, 3, 3, 5, 3, 1, 3, 0, 0, 1, 0, 6,
       0, 0, 5, 0, 5, 1, 3, 6, 0, 5, 0, 0, 5, 0, 1, 0, 0, 0, 5, 5, 0, 5,
       4, 0, 4, 0, 0, 0, 4, 1, 1, 1, 4, 0, 2, 1, 4, 0, 1, 5, 0, 0, 5, 1,
       0, 0, 1, 3, 1, 3, 3, 0, 6, 2, 2, 1, 0, 2, 4, 0, 0, 1, 2, 1, 5, 2,
       1, 1, 0, 3, 3, 1, 0, 1, 6, 0, 0, 3, 5, 0, 0, 3, 1, 0, 0, 1, 0, 2,
       2, 1, 1, 4, 0, 3, 0, 2, 5, 0, 3, 5, 5, 0, 0, 2, 1, 0, 1, 5, 0, 0,
       3, 0, 4, 1, 1, 3, 1, 0, 0, 1, 3, 6, 0, 5, 0, 3, 0, 0, 1, 5, 1, 3,
       4, 4, 1, 1, 5, 2, 0, 5, 1, 3, 5, 5, 5, 0, 0, 6, 3, 1, 0, 0, 1, 0,
       0])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
"precision: ", precision_score(Y_test, prediction, average=None)

('precision: ',
 array([0.91489362, 0.03846154, 0.        , 0.07692308, 0.        ,
        0.23529412, 1.        ]))